'use strict';
const $ = (s, root = document) => root.querySelector(s);
const tg = window.Telegram?.WebApp;
const preview = new URLSearchParams(location.search).get('preview') === '1';
const state = {data:null, people:null, admin:null, report:null, view:'overview', login:null, period:'month', kind:'trades', offset:0, from:'', to:'', busy:false, currency:null};
let generation = 0, refreshTimer, toastTimer;
const paths = {overview:'M3 10l9-7 9 7v10H3z M9 20v-7h6v7',accounts:'M3 7h18v14H3z M3 7V4h14v3 M16 12h5v5h-5z',deals:'M4 5h16 M4 12h16 M4 19h16 M8 2v6 M16 9v6 M9 16v6',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3 M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M17 3a4 4 0 0 1 0 8 M22 21v-3a4 4 0 0 0-3-4',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',plus:'M12 5v14 M5 12h14',arrow:'M5 12h14 M14 7l5 5-5 5',up:'M7 17 17 7 M7 7h10v10',down:'M7 7l10 10 M7 17h10V7',refresh:'M20 7A8 8 0 0 0 6 5L3 8 M3 3v5h5 M4 17a8 8 0 0 0 14 2l3-3 M21 21v-5h-5',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 1v2 M12 21v2 M1 12h2 M21 12h2 M4 4l2 2 M18 18l2 2 M4 20l2-2 M18 6l2-2',chevron:'M9 5l7 7-7 7',chart:'M3 19h18 M4 15l5-5 5 3 6-9',check:'m5 12 4 4L19 6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',back:'M19 12H5 M10 7l-5 5 5 5',shield:'M12 2l9 4v6c0 5-9 10-9 10S3 17 3 12V6z M8 12l3 3 5-6',copy:'M8 8h13v13H8z M16 8V3H3v13h5'};
function icon(name, cls=''){return `<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.chart}"/></svg>`;}
function esc(value){return String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(value, cur='USD', signed=false){if(value==null||!Number.isFinite(Number(value)))return '—';return new Intl.NumberFormat('ru-RU',{style:'currency',currency:cur||'USD',maximumFractionDigits:2,signDisplay:signed?'exceptZero':'auto'}).format(value);}
function number(value){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(value||0);}
function date(value, full=false){return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',...(full?{hour:'2-digit',minute:'2-digit',timeZone:'UTC'}:{})}).format(new Date(value.length===10?value+'T00:00:00Z':value.endsWith('Z')?value:value+'Z'));}
function signedClass(value){return value<0?'negative':'positive';}
function notice(text, warning=false){return `<div class="notice ${warning?'warning':''}">${esc(text)}</div>`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function button(action,text,style='secondary',ico='',attrs=''){return `<button class="button ${style}" data-action="${action}" ${attrs}>${ico?icon(ico):''}<span class="button-label">${esc(text)}</span></button>`;}
const tabs=[['overview','Обзор'],['accounts','Счета'],['deals','Сделки'],['people','Гости'],['settings','Настройки']];
const periods=[['today','День'],['yesterday','Вчера'],['week','Неделя'],['lastweek','Пр. неделя'],['month','Месяц'],['all','Всё время'],['custom','Период']];
function nav(){const html=tabs.map(([id,label])=>`<a href="#${id}" aria-label="${label}" class="${state.view===id?'active':''}" ${state.view===id?'aria-current="page"':''}>${icon(id)}<span>${label}</span></a>`).join('');$('#desktop-nav').innerHTML=html;$('#mobile-nav').innerHTML=html;$('#crumb').textContent=tabs.find(([id])=>id===state.view)?.[1]||'Счёт';}
function header(title,subtitle,action=''){return `<div class="page-head"><div><div class="eyebrow">Ваш капитал в движении</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${action}</div>`;}
function empty(title,text,action=''){return `<div class="empty">${icon('chart')}<h2>${esc(title)}</h2><p>${esc(text)}</p>${action}</div>`;}
function accountBadge(a){return a.status==='pending'?'<span class="badge warning">Ожидает синхронизации</span>':a.status==='stale'?'<span class="badge warning">Данные устарели</span>':`<span class="badge fresh">Синхронизирован</span>`;}
function accountCard(a,i=0){const t=a.totals;return `<a href="#account/${a.login}" class="panel account-card"><div class="strategy-icon ${i%2?'':'green'}">${icon('chart')}</div><div class="account-info"><h3>${esc(a.strategy||a.name)}</h3><p>${esc(a.holder||a.name)} · ${esc(a.login)}</p>${a.status!=='fresh'?accountBadge(a):''}</div><div class="account-money"><b>${t?money(t.now,t.cur):'—'}</b><p class="${signedClass(t?.month_pct)}">${t?`${t.month_pct>=0?'+':''}${number(t.month_pct)}% за месяц`:'Ожидаем данные'}</p></div>${icon('chevron','chevron')}</a>`;}
function chart(points,cur='USD'){if(!points?.length)return empty('Пока без движений','Здесь появится динамика закрытых сделок выбранного счёта.');let total=0;const values=[0,...points.map(p=>total+=Number(p.value)||0)];const min=Math.min(...values),max=Math.max(...values),range=max-min||1;const coords=values.map((v,i)=>[i/(values.length-1)*640,140-(v-min)/range*120]);const d=coords.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ');return `<div class="chart-wrap"><svg viewBox="0 0 640 160" preserveAspectRatio="none" role="img" aria-label="Накопленный результат закрытых сделок: ${esc(money(total,cur))}"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#b6da88" stop-opacity=".18"/><stop offset="100%" stop-color="#b6da88" stop-opacity="0"/></linearGradient></defs>${[20,60,100,140].map(y=>`<path class="chart-grid" d="M0 ${y}H640"/>`).join('')}<path class="chart-area" d="${d} L640,160 L0,160Z"/><path class="chart-line" d="${d}"/><circle cx="640" cy="${coords.at(-1)[1]}" r="3" fill="var(--accent)" stroke="var(--panel)" stroke-width="2"/></svg></div><div class="chart-labels"><span>${date(points[0].day)}</span><span>Закрытые сделки · ${esc(cur)}</span><span>${date(points.at(-1).day)}</span></div>`;}
function stats(items){return `<div class="stats">${items.map(([title,value,note,cls,ico])=>`<div class="panel stat"><div class="stat-title">${esc(title)}${icon(ico||'chart')}</div><div class="stat-value ${cls||''}">${value}</div><div class="stat-note">${esc(note)}</div></div>`).join('')}</div>`;}
function currentAccount(){return state.data.accounts.find(a=>String(a.login)===String(state.login))||state.data.accounts.find(a=>!a.demo&&a.enabled)||state.data.accounts[0];}
function periodTabs(){return `<div class="segmented">${periods.map(([key,label])=>`<button data-action="period" data-value="${key}" class="${state.period===key?'active':''}">${label}</button>`).join('')}</div>`;}
function overview(){const d=state.data, curr=state.currency||Object.keys(d.totals)[0]||'USD', t=d.totals[curr]||{capital:0,pnl:0,month:0,kept:0};const own=d.accounts.filter(a=>!a.demo&&a.enabled), demo=d.accounts.find(a=>a.demo&&a.enabled), acc=currentAccount(), rep=state.report;
 return header(`На связи, ${d.user.name}`,'Вся картина. Спокойный контроль.',button('add','Добавить счёт','secondary','plus'))+
 (d.accounts.some(a=>a.status==='stale')?notice('Часть данных устарела. Показаны последние полученные значения, а не текущий баланс.',true):'')+
 `<div class="dashboard-grid"><div><section class="panel hero"><div class="hero-top"><span class="eyebrow">Мой капитал</span><span class="hero-pill">Без учёта демо-счёта · ${esc(curr)}</span></div><div class="hero-value">${money(t.capital,curr)}</div><div class="hero-bottom"><div><p>Результат за всё время</p><b class="${t.pnl<0?'negative':''}">${money(t.pnl,curr,true)}</b></div><div class="separator"></div><div><p>Прибыль на стратегии</p><b>${money(t.kept,curr)}</b></div></div></section>
 ${Object.keys(d.totals).length>1?`<div class="filterbar"><label class="field no-margin">Валюта сводки<select id="currency">${Object.keys(d.totals).map(c=>`<option ${curr===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div>`:''}
 ${stats([['Результат за месяц',money(t.month,curr,true),'После комиссии брокера',signedClass(t.month),'up'],['Активные стратегии',String(own.length),`${new Set(own.map(a=>a.cabinet)).size} кабинета · личные счета`,'','accounts'],['Свежие данные',`${own.filter(a=>a.status==='fresh').length} / ${own.length}`,'Счета с синхронизацией < 5 мин','','refresh']])}
 <section class="panel chart-panel"><div class="panel-head"><div><h2>Динамика результата</h2><p>${esc(acc?.strategy||acc?.name||'Подключите первый счёт')}</p></div>${periodTabs()}</div>${rep&&!rep.pending?`<div class="chart-summary"><strong class="${signedClass(rep.summary.net_income)}">${money(rep.summary.net_income,rep.currency,true)}</strong><span>${rep.summary.count} сделок за период</span></div>${chart(rep.chart,rep.currency)}`:empty('Здесь будет ваша динамика','Подключите счёт или дождитесь первой синхронизации.')}${rep?.archived?'<p class="stat-note">Сводка включает архив. На графике — только сохранившиеся детали сделок.</p>':''}</section>
 <div class="section-head"><h2>Мои стратегии <span class="muted">${own.length.toString().padStart(2,'0')}</span></h2><a href="#accounts" class="text-link">Все счета ${icon('arrow')}</a></div><div class="account-list">${own.length?own.slice(0,4).map(accountCard).join(''):empty('Начните со своего счёта','Подключите MT5 с инвесторским паролем. Приложение будет показывать сделки и результат.',button('add','Подключить счёт','primary','plus'))}</div></div>
 <aside class="side-stack"><section class="panel side-note"><div class="orbit"></div><div><span class="eyebrow">LESS NOISE. MORE CLARITY.</span><h2>Ваши деньги.<br>В одном ритме.</h2></div><p>Счета, сделки и люди — всё связано с вашим Telegram-ботом.</p></section>
 ${demo?`<section class="panel demo-panel"><span class="eyebrow">Публичная стратегия</span><h3>Наблюдайте за большим.</h3><p>Демо-счёт копитрейдинга. Реальные сделки, отдельная статистика.</p><div class="demo-number">${demo.totals?money(demo.totals.now,demo.totals.cur):'—'}</div><span class="badge demo">Не входит в ваш капитал</span><a class="button" href="#account/${demo.login}">Открыть демо ${icon('arrow')}</a></section>`:''}
 <section class="panel"><h3>Состояние портфеля</h3>${own.slice(0,4).map(a=>`<div class="activity"><div class="activity-icon">${icon(a.status==='fresh'?'check':'clock')}</div><div><p>${esc(a.strategy||a.name)}</p><small>${a.synced?`${a.status==='fresh'?'Обновлён':'Последние данные'} ${date(a.synced,true)} UTC`:'Первое подключение ожидается'}</small></div></div>`).join('')||'<p class="muted mt">Пока нет подключённых счетов.</p>'}</section></aside></div>`;
}
function accountsView(){const items=state.data.accounts;const groups=[...new Set(items.filter(a=>!a.demo).map(a=>a.cabinet||'Без кабинета'))];return header('Ваши счета','Каждая стратегия — на своём месте.',button('add','Добавить счёт','primary','plus'))+groups.map(c=>`<div class="section-head"><h2>${esc(items.find(a=>(a.cabinet||'Без кабинета')===c)?.holder||c)}</h2><div class="inline-actions">${button('cabinet-report','Отчёт','secondary small','',`data-cabinet="${esc(c==='Без кабинета'?'—':c)}"`)}<span class="badge">${esc(c)}</span></div></div><div class="account-list">${items.filter(a=>!a.demo&&(a.cabinet||'Без кабинета')===c).map(accountCard).join('')}</div>`).join('')+(items.some(a=>a.demo)?`<div class="section-head"><h2>Демо-наблюдение</h2><span class="badge demo">Отдельно от личного капитала</span></div>${items.filter(a=>a.demo).map(accountCard).join('')}`:'')+(!items.length?empty('Ваш первый шаг','Подключите счёт и получите единую картину.',button('add','Подключить','primary','plus')):'');}
function tradesTable(rep){if(!rep?.deals?.length)return empty('Нет операций за этот период','Попробуйте другой период. Данные появятся после синхронизации с MT5.');return `<div class="table-wrap"><table class="table"><thead><tr><th>Инструмент / событие</th><th>Дата · UTC</th><th class="optional">Объём</th><th>Результат</th></tr></thead><tbody>${rep.deals.map(r=>`<tr><td><b>${esc(r.is_balance?(r.comment||'Балансовая операция'):r.symbol)}</b><span class="subline">${r.is_balance?'Движение средств':esc(r.side)} · #${esc(r.ticket)}</span></td><td>${date(r.time,true)}</td><td class="optional">${number(r.volume)} лот</td><td class="${signedClass(r.net_income)}">${money(r.net_income,rep.currency,true)}</td></tr>`).join('')}</tbody></table></div><div class="inline-actions mt">${state.offset?button('prev','Назад','secondary small','back'):''}${rep.has_more?button('next','Следующие 50','secondary small','arrow'):''}</div>`;}
function reportFilters(){const acc=currentAccount();return `<div class="filterbar"><select class="filter" id="account-select" aria-label="Счёт">${state.data.accounts.map(a=>`<option value="${a.login}" ${a.login===acc?.login?'selected':''}>${esc(a.name)}${a.demo?' · демо':''}</option>`).join('')}</select>${periodTabs()}</div>${state.period==='custom'?`<div class="field-row"><label class="field">С даты<input type="date" id="from-date" value="${esc(state.from)}"></label><label class="field">По дату<input type="date" id="to-date" value="${esc(state.to)}"></label></div>${button('apply-period','Применить период','secondary small')}`:''}`;}
function dealsView(){const rep=state.report;return header('История в деталях','Сделки, движения средств и итоги по месяцам.')+reportFilters()+`<div class="filterbar"><div class="segmented">${[['trades','Сделки'],['moves','Движения'],['archive','По месяцам']].map(([key,label])=>`<button class="${state.kind===key?'active':''}" data-action="kind" data-value="${key}">${label}</button>`).join('')}</div></div>`+(!rep||rep.pending?empty('Ожидаем данные','Агент ещё не передал историю этого счёта.'):state.kind==='archive'?archive(rep):`<div class="panel">${rep.archived?notice('Часть истории свёрнута в месячные итоги. Детали прежних месяцев доступны во вкладке «По месяцам».'):''}${tradesTable(rep)}</div>`);}
function archive(rep){const max=Math.max(1,...rep.months.map(m=>Math.abs(m.net)));return `<section class="panel"><h2>Месячные результаты</h2><p class="stat-note">Те же расчёты, что в Telegram-боте · после комиссии</p><div class="archive-bars">${rep.months.map(m=>`<div class="archive-item"><span>${esc(m.month)}</span><div class="archive-track"><progress value="${Math.abs(m.net)}" max="${max}" aria-label="Результат ${esc(m.month)}"></progress></div><span class="${signedClass(m.net)}">${money(m.net,rep.currency,true)}</span></div>`).join('')}</div>${!rep.months.length?empty('История ещё не накоплена','Месячные итоги появятся после первой синхронизации.'):''}</section>`;}
function accountView(){const a=currentAccount();if(!a)return empty('Счёт не найден','Возможно, владелец отозвал доступ.');const t=a.totals,rep=state.report;return `<a href="#accounts" class="text-link back">${icon('back')} Все счета</a>`+header(a.strategy||a.name,`${a.holder||a.name} · ${a.login} · ${a.server}`,button('account-settings','Настроить','secondary','settings',`data-login="${a.login}"`))+(a.demo?notice('Демо-наблюдение: этот капитал не входит в вашу личную сводку.'):a.shared?notice('Счёт предоставлен владельцем для наблюдения. Ваши уведомления настраиваются отдельно.'):'' )+(a.status!=='fresh'?notice(a.status==='pending'?'Счёт сохранён. Ожидаем первую успешную синхронизацию.':`Данные устарели. Последняя синхронизация: ${date(a.synced,true)} UTC.`,true):'')+stats([['Капитал',t?money(t.now,t.cur):'—','Реальные вложенные деньги','','accounts'],['Результат за всё время',t?money(t.pnl,t.cur,true):'—','После комиссии брокера',signedClass(t?.pnl),'up'],['Доходность',t?`${number(t.roi)}%`:'—','С учётом движения капитала',signedClass(t?.roi),'chart']])+reportFilters()+(rep&&!rep.pending?`<section class="panel chart-panel"><div class="panel-head"><h2>${esc(rep.title)}</h2><span class="badge">${rep.summary.count} сделок</span></div><div class="chart-summary"><strong class="${signedClass(rep.summary.net_income)}">${money(rep.summary.net_income,rep.currency,true)}</strong><span>чистый результат</span></div>${chart(rep.chart,rep.currency)}</section><div class="section-head"><h2>Последние сделки</h2>${button('full-report','Отчёт бота','secondary small')}</div><div class="panel">${tradesTable(rep)}</div><div class="section-head"><h2>История по месяцам</h2></div>${archive(rep)}`:'');}
function peopleView(){const p=state.people;return header('Ваш круг','Приглашения и доступ к вашим стратегиям.',button('invite','Пригласить','primary','plus'))+(!p?empty('Загружаем гостей','Это займёт несколько секунд.'): `<div class="section-head"><h2>Гости <span class="muted">${p.guests.length}</span></h2></div><div class="cards-grid">${p.guests.map(g=>`<section class="panel people-card"><div class="person-head"><div class="avatar">${esc(g.name.slice(0,1).toUpperCase())}</div><div><h3>${esc(g.name)}</h3><p>${esc(g.since||'Гость по приглашению')}</p></div></div><p>${g.accounts.length} доступных счетов</p>${g.accounts.map(a=>`<div class="settings-row"><p>${esc(a.name)}</p>${button('take','Забрать','secondary small','',`data-guest="${g.id}" data-login="${a.login}"`)}</div>`).join('')}<div class="actions">${button('guest-detail','Подробнее','secondary small','',`data-guest="${g.id}"`)}${button('revoke-guest','Убрать доступ','danger small','',`data-guest="${g.id}"`)}</div></section>`).join('')}</div>${!p.guests.length?empty('Ваш круг пока пуст','Создайте приглашение и выберите счета, которыми хотите поделиться.'):''}<div class="section-head"><h2>Активные приглашения</h2><span class="badge">Одноразовые ссылки</span></div><div class="cards-grid">${p.invites.map(i=>`<section class="panel people-card"><h3>${i.logins.length?`${i.logins.length} счёта для наблюдения`:'Без доступа к счетам'}</h3><p class="invite-url">${esc(i.url)}</p><div class="actions">${button('copy','Скопировать','secondary small','copy',`data-text="${esc(i.url)}"`)}${button('revoke-invite','Отозвать','danger small','',`data-token="${esc(i.token)}"`)}</div></section>`).join('')}</div>${!p.invites.length?'<p class="muted mt">Активных ссылок пока нет.</p>':''}`);}
function toggle(label,note,action,on,attrs=''){return `<div class="settings-row"><div><p>${esc(label)}</p><small>${esc(note)}</small></div><button class="switch" role="switch" aria-label="${esc(label)}" aria-checked="${!!on}" data-action="${action}" ${attrs}></button></div>`;}
function settingsView(){return header('Под ваш ритм','Уведомления, оформление и управление доступом.')+`<div class="two-column"><section class="panel"><h2>Личное пространство</h2>${toggle('Светлая тема','Оформление сохраняется на этом устройстве','theme',document.documentElement.dataset.theme==='light')}<div class="settings-row"><div><p>Синхронизация с ботом</p><small>Изменения сохраняются сразу · обновление каждые 15 сек.</small></div>${icon('refresh')}</div><div class="settings-row"><div><p>Время в отчётах</p><small>UTC — одинаково в приложении и истории сделок</small></div><span class="badge">UTC</span></div></section><section class="panel"><h2>Счета и уведомления</h2>${state.data.accounts.map(a=>`<div class="settings-row"><div><p>${esc(a.name)}</p><small>${a.enabled?'Отслеживание включено':'Скрыт / отслеживание выключено'}</small></div>${button('account-settings','Настроить','secondary small','',`data-login="${a.login}"`)}</div>`).join('')||'<p class="muted mt">Сначала подключите счёт.</p>'}</section></div><div class="section-head"><h2>Кошельки кабинетов</h2></div>${notice('Это расчёт по известным движениям. Внешние выводы не поступают от брокера автоматически. «Обнулить учёт» меняет только отображаемый учёт, деньги не переводятся.')}<div class="cards-grid">${state.data.wallets.map(w=>`<section class="panel"><h3>${esc(w.name)}</h3><div class="stat-value">${number(w.amount)}</div><p class="stat-note">Расчётный остаток кабинета · валюта по данным портала</p><div class="mt">${button('wallet-reset','Обнулить учёт','secondary small','',`data-cabinet="${esc(w.cabinet)}"`)}</div></section>`).join('')}</div>${state.data.founder?`<div class="section-head"><h2>Управление сервисом</h2></div><section class="panel">${toggle('Служебные уведомления','Состояние машин и обновления','alerts',state.data.update_alerts)}<div class="settings-row"><div><p>Сообщение пользователям</p><small>Текст и получатели проверяются перед отправкой</small></div>${button('broadcast','Написать','secondary small')}</div>${state.admin?.machines.map(m=>`<div class="settings-row"><div><p>${esc(m.host)}</p><small>${esc(m.role)} · ${m.seen?date(m.seen,true):'—'} UTC</small></div><span class="badge">${m.host===state.admin.active?'Опрашивает':'Резерв'}</span></div>`).join('')||''}</section>`:`<div class="mt">${button('leave','Отключить мой доступ','danger')}</div>`}`;}
function render(){nav();const views={overview,accounts:accountsView,deals:dealsView,account:accountView,people:peopleView,settings:settingsView};$('#main').innerHTML=(preview?'<div class="preview-label">ПРЕДПРОСМОТР ДИЗАЙНА · Вымышленные данные, без доступа к вашим счетам. Изменения отключены.</div>':'')+(views[state.view]||overview)()+(state.view==='settings'&&state.admin?.network?.length?networkView():'');$('#avatar').textContent=state.data.user.name.slice(0,1).toUpperCase();}
async function api(path,options={}){if(preview){if(options.method&&options.method!=='GET')throw new Error('В предпросмотре изменения отключены');const d=await fetch('preview.json').then(r=>r.json());if(path==='/bootstrap')return d.bootstrap;if(path==='/people')return d.people;if(path==='/admin')return d.admin;if(path.startsWith('/guests/')||path.startsWith('/cabinets/'))return {report:'Демонстрационный отчёт. Вымышленные данные для проверки интерфейса.'};if(path.includes('/report')){const r=structuredClone(d.report);if(new URLSearchParams(path.split('?')[1]).get('kind')==='moves')r.deals=[];return r;}throw new Error('Этот раздел недоступен в предпросмотре');}const response=await fetch(new URL('../api'+path,location.href),{...options,signal:AbortSignal.timeout(path==='/broadcast'?180000:20000),headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...options.headers},cache:'no-store'});const d=await response.json().catch(()=>({error:'Сервер вернул некорректный ответ'}));if(!response.ok)throw new Error(d.error||`Ошибка ${response.status}`);return d;}
async function loadReport(){const acc=currentAccount();if(!acc){state.report=null;return;}state.login=acc.login;const params=new URLSearchParams({period:state.period,kind:state.kind,offset:state.offset});if(state.period==='custom'){if(!state.from||!state.to)return;params.set('from',state.from);params.set('to',state.to);}return api(`/accounts/${acc.login}/report?${params}`);}
async function refresh(quiet=false){if(state.busy){if(!quiet){state.pendingRefresh=true;generation++;}return;}state.busy=true;const gen=++generation;try{const data=await api('/bootstrap');if(gen!==generation)return;state.data=data;let report,people,admin;if(['overview','account','deals'].includes(state.view))report=await loadReport();if(state.view==='people')people=await api('/people');if(state.view==='settings'&&data.founder)admin=await api('/admin');if(gen!==generation)return;if(report)state.report=report;if(people)state.people=people;if(admin)state.admin=admin;$('#connection').textContent=preview?'Демо-просмотр':'Обновлено '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});if(!quiet||!document.querySelector('input:focus,textarea:focus,select:focus'))render();}catch(error){$('#connection').textContent='Нет синхронизации';if(!state.data)$('#main').innerHTML=empty('Ваше пространство в Telegram',error.message,button('refresh','Попробовать снова','primary','refresh'));else if(!quiet)toast(error.message);}finally{state.busy=false;if(state.pendingRefresh){state.pendingRefresh=false;await refresh();}}}
async function navigate(){const [view,login]=location.hash.slice(1).split('/');state.view=['overview','accounts','deals','account','people','settings'].includes(view)?view:'overview';if(login)state.login=Number(login);state.offset=0;state.kind='trades';state.report=null;nav();if(state.data){render();}await refresh();tg?.BackButton?.[state.view==='account'?'show':'hide']();}
function setTheme(theme,persist=true){document.documentElement.dataset.theme=theme;try{if(persist)localStorage.setItem('tag-theme',theme);}catch{}const color=theme==='light'?'#f4f5f0':'#111416';document.querySelector('meta[name="theme-color"]').content=color;try{tg?.setHeaderColor(color);tg?.setBackgroundColor(color);}catch{}if(state.data&&state.view==='settings')render();}
function switchTheme(){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');}
function dialog(title,body,label='Сохранить'){return new Promise(resolve=>{const d=$('#dialog');$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog-submit').textContent=label;d.returnValue='';d.onclose=()=>{const values=Object.fromEntries(new FormData($('form',d)));resolve(d.returnValue==='confirm'?values:null);};$('form',d).onsubmit=e=>{if(e.submitter?.value==='cancel')return;const fields=[...d.querySelectorAll('input,select,textarea')];if(!fields.every(f=>f.reportValidity()))e.preventDefault();};d.showModal();});}
async function confirm(title,text,label='Подтвердить'){return !!await dialog(title,`<p>${esc(text)}</p>`,label);}
async function mutate(path,data,method='POST'){await api(path,{method,body:data===undefined?undefined:JSON.stringify(data)});tg?.HapticFeedback?.notificationOccurred('success');toast('Сохранено. Изменения доступны и в боте.');await refresh();}
function field(label,name,type='text',value='',extra=''){return `<label class="field">${esc(label)}<input type="${type}" name="${name}" value="${esc(value)}" ${extra}></label>`;}
async function configureAccount(login){const a=state.data.accounts.find(a=>a.login===Number(login));if(!a)return;const body=`${a.demo?notice('Демо-счёт: только отображение и уведомления.'):field('Название стратегии','name','text',a.strategy||a.name,'required maxlength="48"')}<label class="check"><input type="checkbox" name="enabled" ${a.enabled?'checked':''}>${a.demo?'Показывать демо-счёт':'Отслеживать счёт'}</label>${[['all','Все уведомления'],['trades','Сделки'],['deposits','Пополнения'],['withdrawals','Выводы']].map(([k,v])=>`<label class="check"><input type="checkbox" name="${k}" ${a.notify?.[k]!==false?'checked':''}>${v}</label>`).join('')}${!a.demo&&!a.shared?field('Привязать капитал Invested (необязательно)','base','number','','min="0" max="1000000000000" step="0.01"')+'<p>Заполняйте только для корректировки капитала на текущую дату.</p>':''}${!a.demo?`<div class="inline-actions mt">${button('delete-account','Удалить из приложения','danger small','',`data-login="${a.login}"`)}${!a.shared?button('restart','Перезапустить терминал','secondary small','',`data-login="${a.login}"`):''}</div>`:''}`;const values=await dialog('Настройки счёта',body);if(!values)return;const data={enabled:values.enabled==='on',notify:Object.fromEntries(['all','trades','deposits','withdrawals'].map(k=>[k,values[k]==='on']))};if(values.name)data.name=values.name;if(values.base!=='')if(values.base!==undefined)data.base=Number(values.base);await mutate(`/accounts/${a.login}`,data,'PATCH');}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();const action=el.dataset.action;if(el.disabled)return;el.disabled=true;try{
 if(action==='refresh')await refresh();
 else if(action==='theme')switchTheme();
 else if(action==='period'){state.period=el.dataset.value;state.offset=0;if(state.period==='custom'){if(state.view==='overview')location.hash='deals';else render();}else await refresh();}
 else if(action==='kind'){state.kind=el.dataset.value;state.offset=0;await refresh();}
 else if(action==='next'||action==='prev'){state.offset=Math.max(0,state.offset+(action==='next'?50:-50));await refresh();}
 else if(action==='apply-period'){state.from=$('#from-date').value;state.to=$('#to-date').value;if(!state.from||!state.to||state.from>state.to)throw new Error('Укажите корректные даты начала и конца');await refresh();}
 else if(action==='add'){const d=await dialog('Подключить счёт MT5',`<p>Используйте инвесторский пароль: он даёт доступ только к просмотру.</p>${field('Название стратегии','name','text','','required maxlength="48"')}${field('Номер счёта MT5','login','number','','required min="1" step="1"')}${field('Инвесторский пароль','password','password','','required maxlength="128" autocomplete="new-password"')}${field('Сервер MT5','server','text','TMFinancials-Server','required maxlength="96"')}<div class="field-row">${field('Владелец кабинета','holder','text','','maxlength="96"')}${field('Кабинет (CU…)','cabinet','text','','maxlength="32"')}</div>`,'Подключить');if(d){await mutate('/accounts',d);location.hash='accounts';}}
 else if(action==='account-settings')await configureAccount(el.dataset.login);
 else if(action==='delete-account'){if($('#dialog').open)$('#dialog').close('cancel');if(await confirm('Удалить счёт?','Он исчезнет из вашего приложения и бота. Торговый счёт у брокера останется.','Удалить')){await mutate(`/accounts/${el.dataset.login}`,undefined,'DELETE');location.hash='accounts';}}
 else if(action==='restart'){if($('#dialog').open)$('#dialog').close('cancel');if(await confirm('Перезапустить терминал?','Это общий терминал агента. Опрос остальных счетов кратковременно прервётся.','Перезапустить'))await mutate('/actions',{action:'restart',login:Number(el.dataset.login)});}
 else if(action==='full-report'){await dialog('Отчёт Telegram-бота',`<div class="report-text">${esc(state.report.report)}</div>`,'Готово');}
 else if(action==='invite'){const own=state.data.accounts.filter(a=>!a.demo&&!a.shared);const d=await dialog('Приглашение в ваш круг',`<p>Ссылка одноразовая. Отметьте счета для просмотра или оставьте приглашение без счетов.</p>${own.map(a=>`<label class="check"><input name="login-${a.login}" type="checkbox">${esc(a.name)}</label>`).join('')}`,'Создать ссылку');if(d){const result=await api('/invites',{method:'POST',body:JSON.stringify({logins:Object.keys(d).filter(k=>k.startsWith('login-')).map(k=>Number(k.slice(6)))})});await refresh();await dialog('Приглашение готово',`<p class="invite-url">${esc(result.url)}</p>${button('copy','Скопировать','secondary','copy',`data-text="${esc(result.url)}"`)}`,'Готово');}}
 else if(action==='copy'){try{await navigator.clipboard.writeText(el.dataset.text);toast('Ссылка скопирована');}catch{throw new Error('Не удалось скопировать автоматически. Выделите и скопируйте ссылку.');}}
 else if(action==='revoke-invite'){if(await confirm('Отозвать приглашение?','Ссылка больше не будет предоставлять доступ.'))await mutate('/invites/'+el.dataset.token,undefined,'DELETE');}
 else if(action==='cabinet-report'){const r=await api('/cabinets/'+encodeURIComponent(el.dataset.cabinet)+'/report?period='+(state.period==='custom'?'month':state.period));await dialog('Отчёт кабинета',`<div class="report-text">${esc(r.report)}</div>`,'Готово');}
 else if(action==='guest-detail'){const r=await api('/guests/'+el.dataset.guest);await dialog('Карточка гостя',`<div class="report-text">${esc(r.report)}</div>`,'Готово');}
 else if(action==='revoke-guest'){if(await confirm('Закрыть доступ гостю?','Гость потеряет доступ к боту и мини-приложению. Его копии счетов будут удалены.','Закрыть доступ'))await mutate('/guests/'+el.dataset.guest,{action:'revoke'});}
 else if(action==='take'){if(await confirm('Забрать счёт у гостя?','Остальные счета гостя сохранятся.'))await mutate('/guests/'+el.dataset.guest,{action:'take',login:Number(el.dataset.login)});}
 else if(action==='wallet-reset'){if(await confirm('Обнулить учёт кошелька?','Расчётный остаток станет нулевым. Деньги брокера не затрагиваются.','Обнулить'))await mutate('/actions',{action:'wallet_reset',cabinet:el.dataset.cabinet});}
 else if(action==='alerts')await mutate('/actions',{action:'update_alerts',value:!state.data.update_alerts});
 else if(action==='leave'){if(await confirm('Отключить доступ?','Счета и приглашения в боте будут удалены. Для возвращения понадобится новое приглашение.','Отключить')){await api('/actions',{method:'POST',body:JSON.stringify({action:'leave'})});state.data=null;await refresh();}}
 else if(action==='broadcast'){const d=await dialog('Сообщение пользователям',`<label class="field">Получатели<select name="target"><option value="all">Все пользователи</option>${state.admin.users.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label><label class="field">Текст сообщения<textarea name="text" required maxlength="3000"></textarea></label>`,'Проверить');if(d&&await confirm('Отправить сообщение?',`Получатель: ${d.target==='all'?'все пользователи':state.admin.users.find(u=>u.id===d.target)?.name}.\n\n${d.text}`,'Отправить')){const r=await api('/broadcast',{method:'POST',body:JSON.stringify({...d,request_id:crypto.randomUUID()})});toast(`Отправлено: ${r.sent}. Не доставлено: ${r.failed}.`);}}
 }catch(error){toast(error.message);}finally{el.disabled=false;}});
document.addEventListener('change',async event=>{try{if(event.target.id==='account-select'){state.login=Number(event.target.value);state.offset=0;if(state.view==='account'){location.hash='account/'+state.login;}else await refresh();}if(event.target.id==='currency'){state.currency=event.target.value;render();}}catch(error){toast(error.message);}});
$('#refresh').innerHTML=icon('refresh');$('#refresh').addEventListener('click',()=>refresh());$('#theme').innerHTML=icon('sun');$('#theme').addEventListener('click',switchTheme);
let savedTheme;try{savedTheme=localStorage.getItem('tag-theme');}catch{}setTheme(savedTheme||(tg?.initData?tg.colorScheme:'dark'),false);
try{tg?.ready();tg?.expand();tg?.BackButton?.onClick(()=>{location.hash='accounts';});tg?.onEvent('themeChanged',()=>{let saved;try{saved=localStorage.getItem('tag-theme');}catch{}if(!saved)setTheme(tg.colorScheme,false);});}catch{}
window.addEventListener('hashchange',navigate);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true);});
navigate();refreshTimer=setInterval(()=>{if(!document.hidden&&!$('#dialog').open&&!(state.view==='deals'&&state.period==='custom'))refresh(true);},15000);

function networkView(){return `<div class="section-head"><h2>Доход партнёрской сети</h2></div><section class="panel"><p class="stat-note">По событиям портала · последние 30 дней с начислениями · валюта портала</p><div class="table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Сделок сети</th><th>Начислено</th></tr></thead><tbody>${state.admin.network.map(d=>`<tr><td>${esc(d.day)}</td><td>${number(d.trades)}</td><td class="positive">${number(d.income)}</td></tr>`).join('')}</tbody></table></div></section>`;}
