'use strict';
const $ = (s, root = document) => root.querySelector(s);
const tg = window.Telegram?.WebApp;
const preview = new URLSearchParams(location.search).get('preview') === '1';
const state = {data:null, people:null, admin:null, report:null, reportError:'', notifications:{items:[],unread:0}, view:'overview', login:null, period:'today', kind:'trades', offset:0, from:'', to:'', filters:{overview:{period:'today',from:'',to:''},deals:{period:'today',from:'',to:''},account:{period:'today',from:'',to:''}}, busy:false, currency:null};
let generation = 0, refreshTimer, toastTimer, notificationsStarted = false, lastNotificationId = 0;
const paths = {overview:'M3 10l9-7 9 7v10H3z M9 20v-7h6v7',accounts:'M3 7h18v14H3z M3 7V4h14v3 M16 12h5v5h-5z',deals:'M4 5h16 M4 12h16 M4 19h16 M8 2v6 M16 9v6 M9 16v6',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3 M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M17 3a4 4 0 0 1 0 8 M22 21v-3a4 4 0 0 0-3-4',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',plus:'M12 5v14 M5 12h14',arrow:'M5 12h14 M14 7l5 5-5 5',up:'M7 17 17 7 M7 7h10v10',down:'M7 7l10 10 M7 17h10V7',refresh:'M20 7A8 8 0 0 0 6 5L3 8 M3 3v5h5 M4 17a8 8 0 0 0 14 2l3-3 M21 21v-5h-5',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 1v2 M12 21v2 M1 12h2 M21 12h2 M4 4l2 2 M18 18l2 2 M4 20l2-2 M18 6l2-2',chevron:'M9 5l7 7-7 7',chart:'M3 19h18 M4 15l5-5 5 3 6-9',check:'m5 12 4 4L19 6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',back:'M19 12H5 M10 7l-5 5 5 5',shield:'M12 2l9 4v6c0 5-9 10-9 10S3 17 3 12V6z M8 12l3 3 5-6',copy:'M8 8h13v13H8z M16 8V3H3v13h5'};
paths.bell='M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9 M10 21h4';paths.exit='M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4 M16 17l5-5-5-5 M21 12H9';paths.palette='M12 3a9 9 0 1 0 0 18c1.4 0 2-.9 2-1.8 0-1.4-1.2-1.6-1.2-2.8 0-.9.7-1.4 1.6-1.4H17a4 4 0 0 0 4-4c0-4.4-4-8-9-8z';
Object.assign(paths,{
 overview:'M4 10.5 12 4l8 6.5V19a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z M9 21v-7h6v7',
 accounts:'M4 6h15a2 2 0 0 1 2 2v12H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h13 M16 12h5v5h-5a2 2 0 0 1 0-5z',
 deals:'M4 19h16 M7 16V9 M12 16V5 M17 16v-5 M5 9h4 M10 5h4 M15 11h4',
 people:'M8.5 11a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z M2 20v-2a5 5 0 0 1 5-5h3a5 5 0 0 1 5 5v2z M17 4a3.5 3.5 0 0 1 0 7 M18 13a4 4 0 0 1 4 4v3',
 settings:'M4 6h16 M4 12h16 M4 18h16 M9 4v4 M16 10v4 M9 16v4',
 chart:'M3 20h18 M5 16l5-5 4 3 5-7 M16 7h3v3',
 refresh:'M20 8a8 8 0 0 0-14-3L3 8 M3 3v5h5 M4 16a8 8 0 0 0 14 3l3-3 M21 21v-5h-5',
 bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9 M10 21h4'
});
function icon(name, cls=''){return `<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.chart}"/></svg>`;}
function esc(value){return String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(value, cur='USD', signed=false){if(value==null||!Number.isFinite(Number(value)))return '—';return new Intl.NumberFormat('ru-RU',{style:'currency',currency:cur||'USD',maximumFractionDigits:2,signDisplay:signed?'exceptZero':'auto'}).format(value);}
function number(value){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(value||0);}
function percent(value){return `${value>=0?'+':''}${new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:3}).format(value)}%`;}
function resultPair(value,cur,pct){return `<span class="result-pair ${signedClass(value)}"><b>${money(value,cur,true)}</b>${pct==null?'':`<small title="Доля от текущего вложенного капитала">${percent(pct)}</small>`}</span>`;}
function date(value, full=false){const raw=String(value||'');const iso=raw.length===10?raw+'T00:00:00Z':/(Z|[+-]\d{2}:\d{2})$/.test(raw)?raw:raw+'Z';return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',...(full?{hour:'2-digit',minute:'2-digit',timeZone:'UTC'}:{})}).format(new Date(iso));}
function dayLabel(value){const text=new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));return text.charAt(0).toUpperCase()+text.slice(1);}
function signedClass(value){return value<0?'negative':'positive';}
function notice(text, warning=false){return `<div class="notice ${warning?'warning':''}">${esc(text)}</div>`;}
function toast(text){const el=$('#toast');el.classList.remove('has-event');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4500);}
function since(value){const raw=String(value||'');const t=Date.parse(/(Z|[+-]\d{2}:\d{2})$/.test(raw)?raw:raw+'Z');if(!Number.isFinite(t))return '';const sec=Math.max(0,(Date.now()-t)/1000);if(sec<60)return 'только что';if(sec<3600)return `${Math.floor(sec/60)} мин назад`;if(sec<86400)return `${Math.floor(sec/3600)} ч назад`;return date(value,true);}
function agoText(sec){if(sec==null)return 'нет данных';if(sec<60)return 'только что';if(sec<3600)return `${Math.floor(sec/60)} мин назад`;if(sec<86400)return `${Math.floor(sec/3600)} ч назад`;return `${Math.floor(sec/86400)} дн назад`;}
function eventKind(item){return ({trades:['Новая сделка','chart'],deposits:['Пополнение','up'],withdrawals:['Вывод','down'],registration:['Новый гость','people'],message:['Сообщение','bell']})[item.kind]||['Событие','bell'];}
function notificationTarget(item){const match=/^trade:(\d+):/.exec(item.event_key||'');if(match&&state.data?.accounts.some(a=>String(a.login)===match[1]))return {hash:'account/'+match[1],label:'Открыть счёт'};if(['trades','deposits','withdrawals'].includes(item.kind))return {hash:'deals',label:'Открыть сделки'};if(item.kind==='registration')return {hash:'people',label:'Открыть гостей'};return {hash:'',label:'Читать'};}
function eventToast(item,count){const el=$('#toast'),[kind,ico]=eventKind(item);el.innerHTML=`<div class="event-toast kind-${esc(item.kind||'other')}" role="alert"><button type="button" class="event-toast-main" data-action="notification-open" data-id="${item.id}"><span class="event-toast-icon">${icon(ico)}</span><span class="event-toast-copy"><b>${count>1?`${count} новых · `:''}${esc(item.title)}</b><span>${esc(item.body)}</span></span><span class="event-toast-go">${icon('arrow')}</span></button><button type="button" class="event-toast-close" data-action="toast-close" aria-label="Закрыть">×</button><i class="event-toast-timer"></i></div>`;el.classList.add('visible','has-event');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),6000);}
function button(action,text,style='secondary',ico='',attrs=''){return `<button type="button" class="button ${style}" data-action="${action}" ${attrs}>${ico?icon(ico):''}<span class="button-label">${esc(text)}</span></button>`;}
function broadcastPreview(text){return esc(text).replace(/&lt;(\/?)(b|i|code|blockquote)&gt;/g,'<$1$2>');}
function fileSize(bytes){return `${number(bytes/1024/1024)} МБ`;}
async function mediaKind(file){const b=new Uint8Array(await file.slice(0,12).arrayBuffer());if(b[0]===255&&b[1]===216&&b[2]===255)return 'photo';if([137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))return 'photo';if(b[4]===102&&b[5]===116&&b[6]===121&&b[7]===112)return 'video';return null;}
const tabs=[['overview','Обзор'],['accounts','Счета'],['deals','Сделки'],['people','Гости'],['settings','Настройки']];
const periods=[['today','Сегодня'],['yesterday','Вчера'],['week','Эта неделя'],['lastweek','Прошлая неделя'],['month','Этот месяц'],['lastmonth','Прошлый месяц'],['all','Всё время'],['custom','Свои даты']];
function nav(){const active=state.view==='account'?'accounts':state.view;const html=tabs.map(([id,label])=>`<a href="#${id}" aria-label="${label}" class="${active===id?'active':''}" ${active===id?'aria-current="page"':''}>${icon(id)}<span>${label}</span></a>`).join('');$('#desktop-nav').innerHTML=html;$('#mobile-nav').innerHTML=html;$('#crumb').textContent=state.view==='account'?'Счета / Счёт':tabs.find(([id])=>id===state.view)?.[1]||'Счёт';}
function header(title,subtitle='',action=''){return `<div class="page-head"><div><h1>${esc(title)}</h1>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div>${action}</div>`;}
function empty(title,text,action=''){return `<div class="empty">${icon('chart')}<h2>${esc(title)}</h2>${text?`<p>${esc(text)}</p>`:''}${action}</div>`;}
function skeleton(kind='list',rows=3){if(kind==='chart')return `<div class="skel skel-chart" aria-busy="true" aria-label="Загружаем"><i class="skel-line w40"></i><i class="skel-line w25 tall"></i><div class="skel-bars">${[40,62,35,78,52,90,44,66,30,58].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div>`;return `<div class="skel skel-list" aria-busy="true" aria-label="Загружаем">${Array.from({length:rows},()=>`<div class="skel-card"><i class="skel-ico"></i><span><i class="skel-line w55"></i><i class="skel-line w35"></i></span><i class="skel-line w20"></i></div>`).join('')}</div>`;}
function notificationItem(i){const [kind,ico]=eventKind(i),target=notificationTarget(i);return `<button type="button" data-action="notification-open" data-id="${i.id}" class="notification-item kind-${esc(i.kind||'other')} ${i.read_at?'':'unread'}"><span class="notification-dot">${icon(ico)}</span><span class="notification-copy"><small class="kicker">${esc(kind)}</small><b>${esc(i.title)}</b><span>${esc(i.body)}</span><small class="meta"><span>${esc(since(i.created_at))}</span><em>${esc(target.label)} ${icon('arrow')}</em></small></span></button>`;}
function notificationPanel(){const items=state.notifications?.items||[],unread=state.notifications?.unread||0;if(!items.length)return `<div class="notification-empty">${icon('bell')}<h3>Событий пока нет</h3></div>`;const today=new Date().toISOString().slice(0,10),yesterday=new Date(Date.now()-864e5).toISOString().slice(0,10),groups=[];for(const i of items){const d=String(i.created_at||'').slice(0,10),label=d===today?'Сегодня':d===yesterday?'Вчера':date(d),last=groups.at(-1);if(last&&last.label===label)last.items.push(i);else groups.push({label,items:[i]});}return `${unread?`<div class="notification-tools">${button('notifications-read','Прочитать всё','secondary small','check')}</div>`:''}<div class="notification-list">${groups.map(g=>`<section class="notification-group"><h3>${esc(g.label)}</h3>${g.items.map(notificationItem).join('')}</section>`).join('')}</div>`;}
function updateNotificationBadge(){const button=$('#notifications');const unread=state.notifications?.unread||0;button.classList.toggle('has-unread',unread>0);button.setAttribute('aria-label',unread?`Уведомления: ${unread} новых`:'Уведомления');}
async function openNotifications(){state.notifications=await api('/notifications');updateNotificationBadge();await dialog('Уведомления',notificationPanel(),'Закрыть');}
async function openNotification(id){const item=state.notifications.items.find(i=>i.id===Number(id));if(!item)return;const d=$('#dialog');if(d.open){const closed=new Promise(resolve=>d.addEventListener('close',resolve,{once:true}));d.close('cancel');await closed;}$('#toast').classList.remove('visible');if(!preview&&!item.read_at){state.notifications=await api('/notifications',{method:'POST',body:JSON.stringify({action:'read',ids:[item.id]})});updateNotificationBadge();}const target=notificationTarget(item);if(target.hash){location.hash=target.hash;return;}await dialog(item.title,`<div class="notification-detail">${esc(item.body).replace(/\n/g,'<br>')}</div>`,'Закрыть');}
async function readAllNotifications(){const ids=(state.notifications?.items||[]).filter(i=>!i.read_at).map(i=>i.id);if(!ids.length)return;if(!preview)state.notifications=await api('/notifications',{method:'POST',body:JSON.stringify({action:'read',ids})});else state.notifications={...state.notifications,unread:0,items:state.notifications.items.map(i=>({...i,read_at:i.read_at||new Date().toISOString()}))};updateNotificationBadge();const body=$('#dialog-body');if(body&&$('#dialog').open)body.innerHTML=notificationPanel();}
async function addShortcut(){const help='<p>Откройте мини-приложение из чата с ботом в Telegram. Нажмите ⋮ справа сверху и выберите «Добавить на главный экран», если этот пункт есть на устройстве.</p><a class="text-link" href="https://t.me/tagmarketgold_bot" target="_blank" rel="noopener">Открыть бота в Telegram</a>';if(preview||!tg?.initData)return dialog('Ярлык Tag Markets',help,'Понятно');if(!tg?.addToHomeScreen)return dialog('Ярлык Tag Markets',help,'Понятно');try{if(tg.checkHomeScreenStatus)tg.checkHomeScreenStatus(s=>{if(s==='added')toast('Ярлык уже добавлен');else if(s==='unsupported')dialog('Ярлык Tag Markets',help,'Понятно');else tg.addToHomeScreen();});else tg.addToHomeScreen();}catch{return dialog('Ярлык Tag Markets',help,'Понятно');}}
function authScreen(){return `<main class="auth-screen"><div class="auth-glow"></div><div class="auth-brand"><div class="auth-mark"><svg viewBox="0 0 64 64" aria-hidden="true"><path class="logo-halo" d="M14.5 19a24 24 0 0 1 32-3M50.5 22a24 24 0 0 1-2 23M43 50.5a24 24 0 0 1-27-3"></path><path class="logo-letter" d="M20 22h24M32 22v22"></path><path class="logo-trend" d="m18 43 8-8 6 4 14-16"></path><circle class="logo-node" cx="46" cy="23" r="2.8"></circle><circle class="logo-seed" cx="18" cy="43" r="1.8"></circle></svg></div><span class="brand-wordmark"><strong>TAG</strong><small>MARKETS</small></span></div><span class="eyebrow">ЛИЧНЫЙ КАБИНЕТ · TELEGRAM MINI APP</span><h1>Ваш капитал<br><em>в одном ритме.</em></h1><p>Откройте приложение из чата с ботом, чтобы увидеть счета, сделки и гостей в защищённом личном пространстве.</p><a class="button primary auth-button" href="https://t.me/tagmarketgold_bot">Открыть бота в Telegram ${icon('arrow')}</a><small>Ссылка на приложение работает только внутри Telegram.</small></main>`;}
function accountBadge(a){return (a.shared?'<span class="badge">Для наблюдения</span>':'')+(!a.enabled?'<span class="badge">На паузе</span>':a.status==='pending'?'<span class="badge warning">Ожидаем данные счёта</span>':'');}
function accountCard(a,i=0,holder=true){const t=a.totals,cur=t?.cur||'USD';return `<a href="#account/${a.login}" class="panel account-card"><div class="strategy-icon ${i%2?'':'green'}">${icon('chart')}</div><div class="account-info"><h3>${esc(a.strategy||a.name)}</h3><p>${holder!==false?`${esc(a.holder||a.name)} · `:'MT5 '}${esc(a.login)}</p>${accountBadge(a)}</div><div class="account-money"><b>${t?money(t.now,cur):'—'}</b>${t?`<p class="${signedClass(t.month_net)}">${money(t.month_net,cur,true)} · ${percent(t.month_pct)}<em> мес.</em></p>`:'<p>Пока нет данных</p>'}</div>${icon('chevron','chevron')}</a>`;}
function countLabel(n,forms){const v=Math.abs(Number(n))%100;const n10=v%10;return `${n} ${v>10&&v<20?forms[2]:n10===1?forms[0]:n10>=2&&n10<=4?forms[1]:forms[2]}`;}
function strategyFamily(a){const name=String(a.strategy||a.name||'').trim();return /sonic|sonik/i.test(name)?'SONIC':/neo/i.test(name)?'NEO':name;}
function sonicStrategyCard(compact=false){
 const account=state.data?.accounts.find(a=>!a.demo&&/sonic|sonik/i.test(`${a.strategy||''} ${a.name||''}`));
 const heading=`<div class="strategy-card-head"><div><span class="eyebrow">НАША СТРАТЕГИЯ</span><h3>SONIC</h3></div><span class="strategy-chip">XAUUSD · золото</span></div>`;
 if(compact)return `<section class="panel strategy-card strategy-card-compact">${heading}${button('strategy-info','О стратегии','secondary small','arrow')}</section>`;
 return `<section class="panel strategy-card strategy-full">${heading}<div class="strategy-facts"><span><b>1–2</b><small>сделки в день</small></span><span><b>0,2–0,5%</b><small>депозита на вход</small></span><span><b>30%</b><small>комиссия с прибыли</small></span></div><div class="risk-line">${icon('shield')}<p>Торговый баланс с плечом можно потерять полностью. Прошлые результаты не гарантируют будущих.</p></div><div class="strategy-links"><a class="text-link" href="https://www.tagmarkets.com/amplify/" target="_blank" rel="noopener">Условия Amplify ${icon('arrow')}</a>${account?`<a class="text-link" href="#account/${account.login}">Мой SONIC ${icon('arrow')}</a>`:''}</div></section>`;
}
function brokerCard(){return `<section class="panel license-card broker-card"><div class="license-card-head"><span class="license-icon">${icon('shield')}</span><div><span class="eyebrow">БРОКЕР И СЧЁТ</span><h2>Tag Markets</h2></div></div><p>Tag Markets — торговое название «T.M. Financials Ltd» (регистрационный номер C185265). Регулируется Комиссией по финансовым услугам (FSC) как инвестиционный дилер, лицензия № GB21026474.</p><div class="license-box"><p>TM FINANCIALS SA (PTY) LTD (рег. № 2024/508189/07) — авторизованный поставщик финансовых услуг (FSP № 55237), регулируется Управлением по финансовому поведению (FSCA). Оказывает только маркетинговые услуги. Торговые счета ведёт, а торговые услуги и ликвидность предоставляет T.M. Financials Ltd.</p></div><div class="license-actions"><a class="button secondary" href="https://www.tagmarkets.com/" target="_blank" rel="noopener">Сайт брокера ${icon('arrow')}</a></div></section>`;}
function sonicGuide(){return brokerCard();}
function compactStrategy(a){const name=a.strategy||a.name;const sonic=/sonic|sonik/i.test(name),neo=/neo/i.test(name);return `<section class="panel detail-strategy"><span class="eyebrow">СТРАТЕГИЯ СЧЁТА</span><div><h2>${esc(name)}</h2><span class="badge">${sonic?'XAUUSD':neo?'NEO':'MT5'}</span></div></section>`;}
function chart(points,cur='USD',archived=false,scope='счёта'){if(!points?.length)return empty('Пока без сделок',`За выбранный период у ${scope} нет закрытых сделок.`);let total=0;const values=[0,...points.map(p=>total+=Number(p.value)||0)];const min=Math.min(...values),max=Math.max(...values),range=max-min||1;const coords=values.map((v,i)=>[i/(values.length-1)*640,140-(v-min)/range*120]);const d=coords.map((p,i)=>`${i?'L':'M'}${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(' ');return `<div class="chart-wrap"><svg viewBox="0 0 640 160" preserveAspectRatio="none" role="img" aria-label="Накопленный результат закрытых сделок: ${esc(money(total,cur))}"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#b6da88" stop-opacity=".18"/><stop offset="100%" stop-color="#b6da88" stop-opacity="0"/></linearGradient></defs>${[20,60,100,140].map(y=>`<path class="chart-grid" d="M0 ${y}H640"/>`).join('')}<path class="chart-area" d="${d} L640,160 L0,160Z"/><path class="chart-line" d="${d}"/><circle cx="640" cy="${coords.at(-1)[1]}" r="3" fill="var(--accent)" stroke="var(--panel)" stroke-width="2"/></svg></div><div class="chart-meta"><span>${archived?'Дат на графике':'Дней с результатом'} <b>${number(points.length)}</b></span><span>Пик <b>${money(max,cur,true)}</b></span><span>Итог <b class="${signedClass(total)}">${money(total,cur,true)}</b></span></div><div class="chart-labels"><span>${date(points[0].day)}</span><span>${archived?'Архив и сделки':'Закрытые сделки'} · ${esc(cur)}</span><span>${date(points.at(-1).day)}</span></div>`;}
function stats(items){return `<div class="stats ${items.length===2?'stats-two':items.length===1?'stats-one':''}">${items.map(([title,value,note,cls,ico])=>`<div class="panel stat"><div class="stat-title">${esc(title)}${icon(ico||'chart')}</div><div class="stat-value ${cls||''}">${value}</div>${note?`<div class="stat-note">${esc(note)}</div>`:''}</div>`).join('')}</div>`;}
function currentAccount(){return state.data.accounts.find(a=>String(a.login)===String(state.login))||state.data.accounts.find(a=>!a.demo&&a.enabled)||state.data.accounts[0];}
function periodTabs(only){const short={today:'Сегодня',week:'Неделя',month:'Месяц',all:'Всё'};const list=only?only.map(k=>[k,short[k]]):periods;return `<div class="segmented ${only?'compact':''}">${list.map(([key,label])=>`<button data-action="period" data-value="${key}" class="${state.period===key?'active':''}">${label}</button>`).join('')}</div>`;}
function spark(points,cur){const rows=(points||[]).slice(-30);if(rows.length<2)return '';const max=Math.max(...rows.map(p=>Math.abs(Number(p.value)||0)),1e-9);return `<div class="spark" role="img" aria-label="Результат по дням">${rows.map(p=>{const v=Number(p.value)||0;return `<i class="${v<0?'neg':''}" style="height:${Math.max(8,Math.round(Math.abs(v)/max*100))}%" title="${esc(date(p.day))}: ${esc(money(v,cur,true))}"></i>`;}).join('')}</div>`;}
function dayExtremes(points,capital,cur){const rows=(points||[]).filter(p=>Number.isFinite(Number(p.value)));if(rows.length<2)return '';const best=rows.reduce((a,b)=>Number(b.value)>Number(a.value)?b:a),worst=rows.reduce((a,b)=>Number(b.value)<Number(a.value)?b:a);const tile=(label,p)=>`<div class="extreme"><small>${label}</small><span class="result-pair ${signedClass(p.value)}"><b>${money(p.value,cur,true)}</b>${capital>0?`<small>${percent(p.value/capital*100)}</small>`:''}</span><em>${esc(date(p.day))}</em></div>`;return `<div class="extremes">${tile('Лучший день',best)}${tile('Худший день',worst)}</div>`;}
function timeMsk(value){return `${String(value||'').slice(11,16)} МСК`;}
function periodBar(){return `<section class="report-controls panel"><div class="report-control report-period">${periodTabs()}</div></section>${customDates()}`;}
function customDates(){return state.period==='custom'?`<div class="custom-period"><div class="field-row"><label class="field">С даты<input type="date" id="from-date" value="${esc(state.from)}"></label><label class="field">По дату<input type="date" id="to-date" value="${esc(state.to)}"></label></div>${button('apply-period','Показать результат','secondary small')}</div>`:'';}
function onboardingCard(){const url=state.data?.onboarding?.registration_url,p=state.data?.onboarding?.progress||{};const step=(key,n,title,body,action)=>`<div class="onboarding-step ${p[key]?'is-done':''}"><div class="onboarding-visual"><b>${p[key]?'✓':n}</b></div><div><h3>${title}</h3><p>${body}</p>${action||''}</div></div>`;return `<section class="panel welcome-card onboarding-card"><span class="eyebrow">ПЕРВЫЙ ЗАПУСК</span><h2>Личный кабинет за 3 шага</h2><div class="onboarding-steps">${step('registered',1,'Регистрация','Создайте профиль в партнёрском портале по персональной ссылке.',url?`<div class="onboarding-actions"><a class="button primary" href="${esc(url)}" target="_blank" rel="noopener">Открыть регистрацию ${icon('arrow')}</a>${p.registered?'':button('onboard-step','Я зарегистрировался','secondary small','check','data-step="registered"')}</div>`:'<p class="muted">Ссылка регистрации ещё не настроена.</p>')}${step('verified',2,'Верификация','Подтвердите почту и пройдите проверку личности в портале.',p.registered?button('onboard-step','Верификация пройдена','secondary small','check','data-step="verified"'):'<small class="muted">Сначала завершите регистрацию</small>')}${step('broker_account',3,'Счёт и стратегия','Создайте счёт Tag Markets, пополните его и добавьте сюда инвесторский пароль MT5.',p.verified?button('onboard-step','Счёт создан','secondary small','check','data-step="broker_account"'):'<small class="muted">Сначала пройдите верификацию</small>')}</div><p class="stat-note">После подключения счёта этот экран исчезнет. Демо-наблюдение остаётся отдельно и не входит в ваш баланс.</p></section>`;}
function overview(){const d=state.data, curr=state.currency||Object.keys(d.totals)[0]||'USD', t=d.totals[curr]||{capital:0,pnl:0,month:0}, own=d.accounts.filter(a=>!a.demo&&!a.shared), demo=d.accounts.find(a=>a.demo&&a.enabled), rep=state.report;
 if(!own.length&&!demo)return header(`Добро пожаловать, ${d.user.name}`)+onboardingCard();
 if(d.onboarding?.needed)return header('Добро пожаловать')+onboardingCard()+sonicGuide();
 const dynamics=state.reportError?empty('Не удалось построить график',state.reportError):rep?`<div class="dynamics-main">${resultPair(rep.summary.net_income,rep.currency,rep.summary.pct_capital)}<span class="muted">${countLabel(rep.summary.count,['сделка','сделки','сделок'])}</span></div>${spark(rep.chart,rep.currency)}${dayExtremes(rep.chart,t.capital,rep.currency)}<a href="#deals" class="text-link chart-details">Все сделки ${icon('arrow')}</a>`:skeleton('chart');
 return header('Мой кабинет','',button('add','Добавить счёт','secondary','plus'))+
  `<div class="dashboard-grid"><div><section class="panel hero"><div class="hero-top"><span class="eyebrow">Мой капитал</span><span class="hero-pill">${esc(curr)}</span></div><div class="hero-value">${money(t.capital,curr)}</div><div class="hero-bottom"><div><p>За всё время</p>${resultPair(t.pnl,curr,t.capital>0?t.pnl/t.capital*100:null)}</div><div class="separator"></div><div><p>Сегодня</p>${resultPair(t.today,curr,t.capital>0?t.today/t.capital*100:null)}</div></div></section>
 ${Object.keys(d.totals).length>1?`<div class="filterbar"><label class="field no-margin">Валюта сводки<select id="currency">${Object.keys(d.totals).map(c=>`<option ${curr===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div>`:''}
  ${stats([['Результат за месяц',resultPair(t.month,curr,t.capital>0?t.month/t.capital*100:null),'',signedClass(t.month),'up']])}
  <section class="panel chart-panel dynamics"><div class="panel-head"><h2>Динамика</h2>${periodTabs(['today','week','month','all'])}</div>${dynamics}</section></div>
 <aside class="side-stack">${sonicStrategyCard(true)}
 ${demo?`<section class="panel demo-panel"><span class="eyebrow">Публичная стратегия</span><h3>Копитрейдинг 45k</h3><div class="demo-number">${demo.totals?money(demo.totals.now,demo.totals.cur):'—'}</div><span class="badge demo">Не входит в ваш капитал</span><a class="button" href="#account/${demo.login}">Открыть ${icon('arrow')}</a></section>`:''}</aside></div>`;
}
function balanceCard(personal){const totals=state.data.totals||{},list=Object.keys(totals);if(!list.length)return '';return `<section class="panel balance-card">${list.map(c=>{const x=totals[c];return `<div class="balance-row"><div><span class="eyebrow">ОБЩИЙ БАЛАНС · ${esc(c)}</span><strong>${money(x.capital,c)}</strong><small>${countLabel(personal.length,['счёт','счёта','счетов'])}</small></div><div class="balance-side"><small>За месяц</small>${resultPair(x.month,c,x.capital>0?x.month/x.capital*100:null)}</div></div>`;}).join('')}</section>`;}
function accountsView(){const items=state.data.accounts,personal=items.filter(a=>!a.demo&&!a.shared),shared=items.filter(a=>a.shared&&!a.demo),demo=items.find(a=>a.demo),groups=[...new Set(personal.map(a=>a.cabinet||'Без кабинета'))];
 const group=c=>{const list=personal.filter(a=>(a.cabinet||'Без кабинета')===c),cur=list.find(a=>a.totals)?.totals?.cur,sum=list.filter(a=>a.totals&&a.totals.cur===cur).reduce((n,a)=>n+a.totals.now,0);return `<section class="account-group"><div class="account-group-head"><div class="group-title"><h2>${esc(list[0]?.holder||c)}</h2><span class="cab-id">${esc(c)}</span>${cur?`<span class="group-sum">${money(sum,cur)}</span>`:''}</div>${button('cabinet-report','Отчёт','secondary small','',`data-cabinet="${esc(c==='Без кабинета'?'—':c)}"`)}</div><div class="account-list">${list.map((a,i)=>accountCard(a,i,false)).join('')}</div></section>`;};
 return header('Счета','',button('add','Добавить счёт','primary','plus'))+(personal.length?balanceCard(personal):'')+groups.map(group).join('')
  +(shared.length?`<section class="account-group"><div class="account-group-head"><div class="group-title"><h2>Для просмотра</h2></div></div><div class="account-list">${shared.map((a,i)=>accountCard(a,i)).join('')}</div></section>`:'')
  +(demo?`<section class="account-group demo-account-group"><div class="account-group-head"><div class="group-title"><span class="eyebrow">ОБЩИЙ СЧЁТ · ПРОСМОТР</span></div>${button('account-settings','Настроить','secondary small','settings',`data-login="${demo.login}"`)}</div><div class="account-list">${accountCard(demo,1)}</div></section>`:'')
  +(!personal.length&&!shared.length?empty('Ваш первый шаг','Подключите счёт.',button('add','Подключить','primary','plus')):'');}
function pager(rep){return `<div class="inline-actions mt">${state.offset?button('prev','Назад','secondary small','back'):''}${rep.has_more?button('next','Ещё 50','secondary small','arrow'):''}</div>`;}
function groupByDay(rep){const days=new Map();for(const deal of rep.deals){const key=String(deal.time).slice(0,10);if(!days.has(key))days.set(key,[]);days.get(key).push(deal);}return days;}
function tradesTable(rep){
 if(!rep?.deals?.length)return rep?.archived?empty('Детали сохранены итогами','Для старых месяцев доступны суммы в истории по месяцам.'):empty('За этот период операций нет','');
 return `<div class="deal-days">${[...groupByDay(rep)].map(([day,rows])=>{const total=rep.day_totals?.[day];return `<section class="deal-day"><div class="deal-day-head"><div><span class="eyebrow">${countLabel(total?.count??rows.length,['операция','операции','операций'])}</span><h3>${esc(dayLabel(day))}</h3></div>${resultPair(total?.net,rep.currency,total?.pct_capital)}</div><div class="deal-day-list">${rows.map(r=>`<article class="deal-row"><div class="deal-symbol"><span class="deal-icon ${r.net_income<0?'loss':''}">${icon(r.net_income<0?'down':'up')}</span><div><b>${esc(r.symbol)}</b><small>${esc(r.side)} · ${number(r.volume)} лот · ${esc(timeMsk(r.time))}</small></div></div><div class="deal-result">${resultPair(r.net_income,rep.currency,r.pct_capital)}</div></article>`).join('')}</div></section>`;}).join('')}</div>${pager(rep)}`;
}
const MOVE={deposit:['Пополнение стратегии','up','in'],reinvest:['Реинвест профита в капитал','refresh','re'],profit_out:['Вывод профита на баланс Tag Markets','down','out'],profit_in:['Профит вернулся на стратегию','up','in'],capital_out:['Вывод капитала на баланс Tag Markets','down','out']};
function moveRow(r,cur){const [label,ico,dir]=MOVE[r.move]||['Движение средств','chart','in'];return `<article class="deal-row move-row ${dir}"><div class="deal-symbol"><span class="deal-icon move-${dir}">${icon(ico)}</span><div><b>${label}</b><small>${esc(timeMsk(r.time))}</small>${r.capital_now!=null?`<small class="flow">Капитал ${number(r.capital_was)} → <b>${money(r.capital_now,cur)}</b></small>`:''}</div></div><div class="deal-result"><span class="result-pair ${signedClass(r.net_income)}"><b>${money(r.net_income,cur,true)}</b></span></div></article>`;}
function stepChart(series){const v=series.map(p=>Number(p.capital)),n=v.length,min=Math.min(...v),max=Math.max(...v),range=max-min||1,x=i=>i/(n-1)*640,y=val=>128-(val-min)/range*100;let d=`M${x(0)},${y(v[0])}`;for(let i=1;i<n;i++)d+=` H${x(i)} V${y(v[i])}`;return `<div class="chart-wrap"><svg viewBox="0 0 640 150" preserveAspectRatio="none" role="img" aria-label="Изменение капитала стратегии"><path class="chart-area" d="${d} V150 H0Z"/><path class="chart-line" d="${d}"/>${v.map((val,i)=>`<circle cx="${x(i)}" cy="${y(val)}" r="3.5" fill="var(--accent)" stroke="var(--panel)" stroke-width="2"/>`).join('')}</svg></div><div class="chart-labels"><span>${date(series[0].time)}</span><span>${countLabel(n-1,['изменение','изменения','изменений'])}</span><span>${date(series.at(-1).time)}</span></div>`;}
function capitalPanel(rep){const s=rep.capital_series||[];if(s.length<2)return '';const first=Number(s[0].capital),last=Number(s.at(-1).capital);return `<section class="panel capital-panel"><div class="panel-head"><div><span class="eyebrow">БАЛАНС СТРАТЕГИИ</span><h2>${money(last,rep.currency)}</h2></div><span class="result-pair ${signedClass(last-first)}"><b>${money(last-first,rep.currency,true)}</b>${first>0?`<small>${percent((last-first)/first*100)}</small>`:''}</span></div>${stepChart(s)}</section>`;}
function siteMoves(rep){if(!rep.site_moves?.length)return '';return `<section class="panel site-moves"><div class="panel-head"><h2>На сайте Tag Markets</h2></div>${rep.site_moves.map(m=>`<article class="deal-row move-row in"><div class="deal-symbol"><span class="deal-icon move-in">${icon('up')}</span><div><b>Пополнение кабинета</b><small>${esc(date(m.time,true))} МСК</small></div></div><div class="deal-result"><span class="result-pair positive"><b>${money(m.amount,m.currency,true)}</b></span></div></article>`).join('')}</section>`;}
function movesView(rep){const cur=rep.currency,fee=rep.commission_count?`<section class="panel fee-card"><div><span class="eyebrow">КОМИССИЯ БРОКЕРА · 30%</span><b>${money(rep.commission_total,cur)}</b></div><small>${countLabel(rep.commission_count,['удержание','удержания','удержаний'])}</small></section>`:'';const list=rep.deals?.length?`<div class="deal-days">${[...groupByDay(rep)].map(([day,rows])=>`<section class="deal-day"><div class="deal-day-head"><div><h3>${esc(dayLabel(day))}</h3></div></div><div class="deal-day-list">${rows.map(r=>moveRow(r,cur)).join('')}</div></section>`).join('')}</div>${pager(rep)}`:empty('За этот период движений нет','');return fee+capitalPanel(rep)+siteMoves(rep)+`<div class="section-head"><h2>Движения средств</h2></div>`+list;}
function dealHighlights(rep){const items=[['week','Эта неделя'],['lastweek','Прошлая неделя'],['month','Этот месяц'],['all','Всё время']];return `<div class="deal-highlights">${items.map(([key,label])=>{const item=rep.insights?.[key];return `<button type="button" data-action="period" data-value="${key}" class="deal-highlight ${state.period===key?'active':''}"><span>${label}</span><b class="${signedClass(item?.net)}">${item?.available===false?'—':money(item?.net,rep.currency,true)}</b>${item?.pct_capital!=null?`<small>${percent(item.pct_capital)}</small>`:''}</button>`;}).join('')}</div>`;}
function accountPicker(){const acc=currentAccount(),list=state.data.accounts;if(list.length<2)return '';return `<div class="account-chips" role="tablist" aria-label="Счёт">${list.map(a=>`<button type="button" role="tab" data-action="pick-account" data-login="${a.login}" aria-selected="${Number(a.login)===Number(acc?.login)}" class="chip ${Number(a.login)===Number(acc?.login)?'active':''}"><b>${esc(a.strategy||a.name)}</b><small>${esc(a.demo?'общий счёт':String(a.holder||a.cabinet||a.login).split(' ')[0])}</small></button>`).join('')}</div>`;}
function reportFilters(){return `<section class="report-controls panel">${accountPicker()}<div class="report-control report-period">${periodTabs()}</div></section>${customDates()}`;}
function dealsView(){
 const rep=state.report;
 const switches=`<div class="deal-switches">${[['trades','Сделки'],['moves','Движения средств'],['archive','По месяцам']].map(([key,label])=>`<button type="button" class="${state.kind===key?'active':''}" data-action="kind" data-value="${key}">${label}</button>`).join('')}</div>`;
 const start=header('Сделки')+reportFilters()+switches;
 if(state.reportError)return start+empty('Не удалось открыть отчёт',state.reportError);
 if(!rep)return start+(state.period==='custom'&&!state.from?empty('Выберите даты',''):skeleton('list',4));
 if(rep.pending)return start+empty('Ожидаем данные','История этого счёта ещё не поступила.');
 if(state.kind==='archive')return start+archive(rep);
 if(state.kind==='moves')return start+movesView(rep);
 const summary=`<section class="panel deals-overview"><div><span class="eyebrow">${esc(rep.title)} · ПОСЛЕ КОМИССИИ</span><div class="deals-overview-result">${resultPair(rep.summary.net_income,rep.currency,rep.summary.pct_capital)}</div><p>${countLabel(rep.summary.count,['закрытая сделка','закрытые сделки','закрытых сделок'])}</p></div>${icon('chart')}</section>${dealHighlights(rep)}`;
 return start+summary+(rep.archived?notice('Ранние сделки сохранены итогами по месяцам.'):'' )+tradesTable(rep);
}
function archive(rep){const max=Math.max(1,...rep.months.map(m=>Math.abs(m.net)));return `<section class="panel archive-panel"><div class="archive-head"><div><span class="eyebrow">ИСТОРИЯ</span><h2>Результат по месяцам</h2></div><span class="badge">${rep.months.length} мес.</span></div><div class="archive-bars">${rep.months.map(m=>`<div class="archive-item"><div class="archive-month"><b>${esc(new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${m.month}-01T12:00:00Z`)))}</b>${resultPair(m.net,rep.currency,m.pct_capital)}</div><div class="archive-track ${m.net<0?'is-negative':''}"><progress value="${Math.abs(m.net)}" max="${max}" aria-label="Результат ${esc(m.month)}"></progress></div></div>`).join('')}</div>${!rep.months.length?empty('История ещё не накоплена','Месячные итоги появятся после первой синхронизации.'):''}</section>`;}
function accountView(){
 const a=currentAccount();
 if(!a)return empty('Счёт не найден','Возможно, владелец отозвал доступ.');
 const t=a.totals,rep=state.report,cur=t?.cur||'USD';
 const pct=value=>t?.now>0?Number(value||0)/t.now*100:null;
 const identity=`<div class="detail-identity"><span><small>Владелец</small><b>${esc(a.holder||'Определяется по терминалу')}</b></span><span><small>Кабинет</small><b>${esc(a.cabinet||'—')}</b></span><span><small>Счёт MT5</small><b>${esc(a.login)}</b></span></div>`;
 const intro=`<div class="detail-top"><a href="#accounts" class="text-link back">${icon('back')} Все счета</a>${button('account-settings','Настроить','secondary','settings',`data-login="${a.login}"`)}</div><section class="panel detail-hero"><div class="detail-hero-heading"><div class="strategy-icon green">${icon('chart')}</div><div><span class="eyebrow">СТРАТЕГИЯ</span><h1>${esc(a.strategy||a.name)}</h1>${a.demo?'<p>Общий счёт</p>':a.shared?'<p>Только просмотр</p>':''}</div></div>${identity}<div class="detail-balance"><span>Мой капитал</span><strong>${t?money(t.now,cur):'—'}</strong></div></section>`;
 const results=t?`<div class="detail-results"><div class="panel detail-result"><span>Сегодня</span>${resultPair(t.today_net,cur,pct(t.today_net))}</div><div class="panel detail-result"><span>Этот месяц</span>${resultPair(t.month_net,cur,pct(t.month_net))}</div><div class="panel detail-result"><span>Всё время</span>${resultPair(t.pnl,cur,pct(t.pnl))}<small>ROI ${percent(t.roi)}</small></div></div>`:'';
 const report=state.reportError?empty('Не удалось открыть историю',state.reportError):rep?.pending?empty('Ожидаем первые данные','Как только терминал прочитает счёт, данные появятся здесь.'):rep?`<section class="panel chart-panel detail-chart"><div class="panel-head"><div><span class="eyebrow">ДИНАМИКА</span><h2>${esc(rep.title)}</h2></div><span class="badge">${countLabel(rep.summary.count,['сделка','сделки','сделок'])}</span></div><div class="chart-summary">${resultPair(rep.summary.net_income,rep.currency,rep.summary.pct_capital)}</div>${chart(rep.chart,rep.currency,rep.archived)}${dayExtremes(rep.chart,t?.now,rep.currency)}<div class="detail-links"><a href="#deals" class="text-link">Сделки и движения средств ${icon('arrow')}</a>${button('full-report','Отчёт','secondary small')}</div></section><div class="section-head"><h2>По месяцам</h2></div>${archive(rep)}`:`<section class="panel">${skeleton('chart')}</section>`;
 return intro+(a.status==='pending'?notice('Счёт подключён. Ожидаем первые данные из MT5.'):'' )+results+periodBar()+report;
}
function linkCard(p){const partner=p.partner_url,share=p.link?`https://t.me/share/url?url=${encodeURIComponent(p.link)}&text=${encodeURIComponent('Приглашаю в Tag Markets')}`:'';return `<section class="panel link-card"><span class="eyebrow">ВАША ССЫЛКА-ПРИГЛАШЕНИЕ</span><div class="link-step ${partner?'done':'todo'}"><span class="step-n">${partner?'✓':'1'}</span><div><b>Партнёрская ссылка</b><small>${partner?'Сохранена':'IB Portal → Partner'}</small></div>${partner?button('partner-link','Изменить','secondary small'):''}</div>${partner?'':`<a class="button primary wide site-link" href="https://exfusion.ibportal.io" target="_blank" rel="noopener">Открыть партнёрский сайт ${icon('arrow')}</a>${button('partner-link','Вставить ссылку','secondary wide','link')}`}<div class="link-step ${p.link?'done':'todo'}"><span class="step-n">${p.link?'✓':'2'}</span><div><b>Ссылка для гостей</b><small>Одна и постоянная</small></div></div>${p.link?`<div class="invite-url">${esc(p.link)}</div><div class="link-actions">${button('copy','Скопировать','secondary','copy',`data-text="${esc(p.link)}"`)}<a class="button primary" href="${esc(share)}" target="_blank" rel="noopener">${icon('arrow')} Отправить</a>${button('renew-link','Обновить','secondary small','refresh')}</div>`:''}</section>`;}
function guestCard(g,p){const have=new Set(g.accounts.filter(a=>a.shared).map(a=>String(a.login))),canShare=(p.shareable||[]).filter(a=>!have.has(String(a.login)));return `<section class="panel people-card"><div class="person-head"><div class="avatar">${esc(g.name.slice(0,1).toUpperCase())}</div><div><h3>${esc(g.name)}</h3>${g.since?`<p>${esc(g.since)}</p>`:''}</div></div><p>${countLabel(g.accounts.length,['счёт','счёта','счетов'])}</p>${g.accounts.map(a=>`<div class="settings-row"><p>${esc(a.name)} <small>${a.shared?'Ваш счёт у гостя':'Личный счёт · только просмотр'}</small></p>${a.shared?button('take','Забрать','secondary small','',`data-guest="${g.id}" data-login="${a.login}"`):''}</div>`).join('')}<div class="actions">${canShare.length?button('share-accounts','Открыть счета','secondary small','plus',`data-guest="${g.id}"`):''}${button('guest-detail','Подробнее','secondary small','',`data-guest="${g.id}"`)}${button('revoke-guest','Убрать доступ','danger small','',`data-guest="${g.id}"`)}</div></section>`;}
function peopleView(){const p=state.people;if(!p)return header('Гости')+skeleton('list',2);return header('Гости')+linkCard(p)+`<div class="section-head"><h2>Приглашены <span class="muted">${p.guests.length}</span></h2></div>${p.guests.length?`<div class="cards-grid">${p.guests.map(g=>guestCard(g,p)).join('')}</div>`:empty('Гостей пока нет','')}`;}
function toggle(label,note,action,on,attrs=''){return `<div class="settings-row"><div><p>${esc(label)}</p>${note?`<small>${esc(note)}</small>`:''}</div><button class="switch" role="switch" aria-label="${esc(label)}" aria-checked="${!!on}" data-action="${action}" ${attrs}></button></div>`;}
const MACHINE_STATE={polling:['Опрашивает','ok'],waiting:['Готова','ok'],legacy:['Старый код','warning'],offline:['Офлайн','muted']};
function machineRow(m){const [label,cls]=MACHINE_STATE[m.state]||MACHINE_STATE.offline;return `<div class="machine-row state-${esc(m.state)}"><div class="machine-top"><b>${esc(m.host)}</b><span class="badge ${cls}">${label}</span></div><small>${m.role==='primary'?'Основная':m.role==='standby'?'Резервная':'Роль не определена'} · ${esc(agoText(m.idle))}${m.commit?` · <code>${esc(m.commit)}</code>`:''}</small>${m.blocked?`<p class="machine-warn">Обновление заблокировано: ${esc(m.blocked)}</p>`:''}</div>`;}
function serviceSummary(machines){const polling=machines.find(m=>m.state==='polling'),legacy=machines.filter(m=>m.state==='legacy'),ready=machines.filter(m=>m.state==='waiting');const rows=[polling?`<div class="service-status ok"><b>Терминал опрашивает</b><span>${esc(polling.host)}</span></div>`:`<div class="service-status bad"><b>Терминал никто не опрашивает</b><span>Данные не обновляются</span></div>`];for(const m of legacy)rows.push(`<div class="service-status warn"><b>${esc(m.host)}: старый код</b><span>Не заменит основную машину — нужно обновить</span></div>`);if(polling&&!ready.length&&!legacy.length)rows.push('<div class="service-status warn"><b>Резерва на связи нет</b><span>Если основная выключится, замены не будет</span></div>');return rows.join('');}
function servicePanel(){const machines=state.admin?.machines||[];return `<section class="panel service-panel"><div class="service-head"><div><span class="eyebrow">ДЛЯ ВЛАДЕЛЬЦА</span><h2>Сервис</h2></div>${button('refresh','Обновить','secondary small','refresh')}</div>${state.admin?`${serviceSummary(machines)}<div class="machine-list">${machines.map(machineRow).join('')||'<p class="muted">Машины не отвечали.</p>'}</div>`:'<p class="muted mt">Загружаем состояние…</p>'}${toggle('Уведомления о сервисе','','alerts',state.data.update_alerts)}<div class="settings-row"><div><p>Сообщение пользователям</p></div>${button('broadcast','Написать','secondary small')}</div></section>`;}
const BRAND_SVG='<svg viewBox="0 0 64 64" aria-hidden="true"><path class="logo-halo" d="M14.5 19a24 24 0 0 1 32-3M50.5 22a24 24 0 0 1-2 23M43 50.5a24 24 0 0 1-27-3"></path><path class="logo-letter" d="M20 22h24M32 22v22"></path><path class="logo-trend" d="m18 43 8-8 6 4 14-16"></path><circle class="logo-node" cx="46" cy="23" r="2.8"></circle><circle class="logo-seed" cx="18" cy="43" r="1.8"></circle></svg>';
function schemePicker(){const cur=currentScheme();return `<div class="scheme-picker" role="radiogroup" aria-label="Цветовая гамма">${SCHEMES.map(([id,name,,,sw])=>`<button type="button" role="radio" aria-checked="${cur===id}" class="scheme ${cur===id?'active':''}" data-action="scheme" data-value="${id}"><span class="swatch" style="background:${sw[0]}"><i style="background:${sw[1]}"></i><i style="background:${sw[2]}"></i></span><b>${name}</b></button>`).join('')}</div>`;}
function settingsView(){const personal=state.data.accounts.filter(a=>!a.demo&&!a.shared),demo=state.data.accounts.find(a=>a.demo);return header('Настройки')+`<div class="two-column"><section class="panel"><span class="eyebrow">ЦВЕТОВАЯ ГАММА</span>${schemePicker()}<button class="shortcut-card" type="button" data-action="shortcut"><span class="shortcut-tile">${BRAND_SVG}</span><span class="shortcut-copy"><b>Ярлык на экран</b><small>Открывать Tag Markets в один тап</small></span><span class="pill">Добавить</span></button></section><section class="panel"><h2>Мои счета</h2>${personal.map(a=>`<div class="settings-row"><div><p>${esc(a.strategy||a.name)}</p><small>${esc(a.cabinet||a.login)}</small></div>${button('account-settings','Настроить','secondary small','',`data-login="${a.login}"`)}</div>`).join('')||'<p class="muted mt">Счетов пока нет.</p>'}</section></div>${demo?`<section class="panel demo-settings"><div class="demo-settings-head"><div><span class="eyebrow">ОБЩИЙ СЧЁТ</span><h2>Копитрейдинг 45k</h2></div><span class="badge demo">Просмотр</span></div><div class="inline-actions">${button('account-settings','Уведомления','secondary','settings',`data-login="${demo.login}"`)}<a class="button secondary" href="#account/${demo.login}">Открыть ${icon('arrow')}</a></div></section>`:''}${brokerCard()}${state.data.founder?servicePanel():`<section class="panel leave-card"><div><b>Доступ</b><small>Счета и данные будут удалены</small></div><button type="button" class="leave-btn" data-action="leave">${icon('exit')}<span>Отключить мой доступ</span></button></section>`}`;}
function render(){nav();const views={overview,accounts:accountsView,deals:dealsView,account:accountView,people:peopleView,settings:settingsView};$('#main').innerHTML=(preview?'<div class="preview-label">Демо-режим · вымышленные данные. Отправка сообщений и управление счетами работают только при запуске из <a href="https://t.me/tagmarketgold_bot" target="_blank" rel="noopener">бота в Telegram</a>.</div>':'')+(views[state.view]||overview)()+(state.view==='settings'&&state.admin?.network?.length?networkView():'');$('#avatar').textContent=state.data.user.name.slice(0,1).toUpperCase();document.querySelectorAll('.segmented').forEach(strip=>{const active=strip.querySelector('.active');if(active)strip.scrollLeft+=active.getBoundingClientRect().left-strip.getBoundingClientRect().left-(strip.clientWidth-active.clientWidth)/2;});}
function previewData(d){
 const now=new Date(Date.now()+3*3600000),today=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));
 const source=new Date('2026-09-16T00:00:00Z'),delta=today-source;
 const shifted=day=>new Date(Date.parse(`${day}T00:00:00Z`)+delta).toISOString().slice(0,10);
 const round=value=>Math.round(value*100)/100;
 const dealToday=round(d.report.deals.reduce((sum,row)=>sum+row.net_income,0));
 const originalLast=d.report.chart.at(-1).value;
 d.report.chart[0].value=round(d.report.chart[0].value-(dealToday-originalLast));
 d.report.chart.at(-1).value=dealToday;
 d.report.chart.forEach(point=>{point.day=shifted(point.day)});
 d.report.deals.forEach(row=>{row.time=shifted(row.time.slice(0,10))+row.time.slice(10)});
 d.report.day_totals={[shifted('2026-09-16')]:{count:d.report.deals.length,net:dealToday}};
 d.report.months.forEach(month=>{const [year,index]=month.month.split('-').map(Number);const next=new Date(Date.UTC(today.getUTCFullYear(),today.getUTCMonth()+(year-2026)*12+index-9,1));month.month=next.toISOString().slice(0,7)});
 let totalToday=0;
 for(const account of d.bootstrap.accounts){if(!account.totals)continue;account.totals.today_net=round(dealToday*account.totals.month_net/d.report.summary.net_income);if(!account.demo&&!account.shared)totalToday+=account.totals.today_net;}
 d.bootstrap.totals.USD.today=round(totalToday);
 const overviewLast=d.overview_report.chart.at(-1).value;
 d.overview_report.chart[0].value=round(d.overview_report.chart[0].value-(totalToday-overviewLast));
 d.overview_report.chart.at(-1).value=round(totalToday);
 d.overview_report.chart.forEach(point=>{point.day=shifted(point.day)});
 return d;
}
function previewBounds(period,params){
 const now=new Date(Date.now()+3*3600000),day=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));
 const key=value=>value.toISOString().slice(0,10),move=(date,n)=>new Date(date.getTime()+n*86400000);
 const monday=move(day,-(day.getUTCDay()+6)%7),month=new Date(Date.UTC(day.getUTCFullYear(),day.getUTCMonth(),1));
 if(period==='today')return [key(day),key(day)];
 if(period==='yesterday')return [key(move(day,-1)),key(move(day,-1))];
 if(period==='week')return [key(monday),key(day)];
 if(period==='lastweek')return [key(move(monday,-7)),key(move(monday,-1))];
 if(period==='month')return [key(month),key(day)];
 if(period==='lastmonth')return [key(new Date(Date.UTC(day.getUTCFullYear(),day.getUTCMonth()-1,1))),key(move(month,-1))];
 if(period==='custom')return [params.get('from')||'9999-12-31',params.get('to')||'0000-01-01'];
 return ['0000-01-01','9999-12-31'];
}
function previewReport(d,path,overview){
 const params=new URLSearchParams(path.split('?')[1]),period=params.get('period')||'today';
 const r=structuredClone(overview?d.overview_report:d.report);
 const account=overview?null:d.bootstrap.accounts.find(a=>String(a.login)===path.match(/accounts\/(\d+)/)?.[1]);
 const scale=account?.totals?account.totals.month_net/d.report.summary.net_income:1;
 const capital=overview?d.bootstrap.totals.USD.capital:account?.totals?.now||0;
 const monthNet=overview?d.overview_report.summary.net_income:account?.totals?.month_net||d.report.summary.net_income;
 const allNet=overview?d.bootstrap.totals.USD.pnl:account?.totals?.pnl||d.report.months.reduce((sum,item)=>sum+item.net,0);
 const archivedBase=d.report.months.slice(0,-1).reduce((sum,item)=>sum+item.net,0);
 r.months=d.report.months.map((item,index)=>{const net=index===d.report.months.length-1?monthNet:(allNet-monthNet)*item.net/archivedBase;return {month:item.month,count:item.count*(overview?2:1),net:Math.round(net*100)/100,pct_capital:capital>0?Math.round(net/capital*1000)/10:null}});
 if(!overview){
  r.chart.forEach(point=>{point.value=Math.round(point.value*scale*100)/100});
  r.deals.forEach(row=>{row.net_income=Math.round(row.net_income*scale*100)/100;row.pct_capital=capital>0?Math.round(row.net_income/capital*10000)/100:null;row.ticket+=Number(account?.login||10001)-10001;if(account?.login===10002)row.symbol='EURUSD'});
 }
 const sourceChart=[...r.chart];
 const insight=key=>{const [begin,end]=previewBounds(key,params);const net=key==='all'?allNet:Math.round(sourceChart.filter(point=>point.day>=begin&&point.day<=end).reduce((sum,point)=>sum+point.value,0)*100)/100;return {available:true,net,pct_capital:capital>0?Math.round(net/capital*1000)/10:null}};
 if(!overview)r.insights=Object.fromEntries(['week','lastweek','month','all'].map(key=>[key,insight(key)]));
 const [from,to]=previewBounds(period,params);
 r.chart=r.chart.filter(point=>point.day>=from&&point.day<=to);
 if(period==='lastmonth'&&!r.chart.length){const month=r.months?.find(item=>item.month===from.slice(0,7));if(month)r.chart=[{day:to,value:month.net}];}
 if(period==='all'&&r.months){const older=r.months.slice(0,-1).map(item=>({day:`${item.month}-28`,value:item.net}));r.chart=[...older,...r.chart];}
 if(!overview){
  r.deals=r.deals.filter(row=>row.time.slice(0,10)>=from&&row.time.slice(0,10)<=to);
  r.day_totals=r.deals.length?{[r.deals[0].time.slice(0,10)]:{count:r.deals.length,net:Math.round(r.deals.reduce((sum,row)=>sum+row.net_income,0)*100)/100}}:{};
  for(const item of Object.values(r.day_totals))item.pct_capital=capital>0?Math.round(item.net/capital*1000)/10:null;
  if(params.get('kind')==='moves'){const day=n=>new Date(Date.now()+3*3600000-n*864e5).toISOString().slice(0,10);r.deals=[{ticket:9,time:`${day(1)}T14:32:10Z`,is_balance:true,move:'reinvest',net_income:6.92,capital_was:1280.14,capital_now:1287.06},{ticket:8,time:`${day(3)}T09:05:41Z`,is_balance:true,move:'deposit',net_income:250,capital_was:1030.14,capital_now:1280.14},{ticket:7,time:`${day(6)}T18:20:00Z`,is_balance:true,move:'profit_out',net_income:-40.5}];r.day_totals={};r.commission_total=48.6;r.commission_count=3;r.capital_series=[{time:`${day(6)}T00:00:00Z`,capital:1030.14},{time:`${day(3)}T09:05:41Z`,capital:1280.14},{time:`${day(1)}T14:32:10Z`,capital:1287.06}];r.site_moves=[{kind:'deposit',amount:250,currency:'USD',time:`${day(3)}T09:04:12Z`}];}
  r.archived=period==='all'||(r.chart.length>0&&!r.deals.length);
 }
 const net=period==='all'?allNet:Math.round(r.chart.reduce((sum,point)=>sum+point.value,0)*100)/100;
 r.summary.net_income=net;
 r.summary.pct_capital=capital>0?Math.round(net/capital*1000)/10:null;
 r.summary.count=period==='today'?(overview?d.report.deals.length*2:r.deals.length):period==='lastmonth'?r.months.at(-2)?.count||0:period==='all'?r.months.reduce((sum,item)=>sum+item.count,0):Math.round((overview?d.overview_report.summary.count:d.report.summary.count)*r.chart.length/(overview?d.overview_report.chart.length:d.report.chart.length));
 r.title=Object.fromEntries(periods)[period]||'Выбранный период';
 return r;
}
async function api(path,options={}){
 if(preview){
  if(path==='/notifications'){const at=m=>new Date(Date.now()-m*60000).toISOString();return {items:[{id:4,kind:'trades',event_key:'trade:10001:123',title:'SONIC · новая сделка',body:'XAUUSD · результат +18,42 $',created_at:at(3),read_at:null},{id:3,kind:'deposits',title:'Пополнение',body:'На счёт NEO.FX зачислено 250,00 $',created_at:at(95),read_at:null},{id:2,kind:'message',title:'Сообщение от сервиса',body:'Завтра с 03:00 до 03:10 возможны короткие перерывы в обновлении данных.',created_at:at(60*30),read_at:at(60*20)},{id:1,kind:'registration',title:'Новый гость',body:'Виктория Орлова приняла приглашение',created_at:at(60*52),read_at:at(60*50)}],unread:2};}
  if(options.method&&options.method!=='GET')throw new Error('В предпросмотре изменения отключены');
  const d=previewData(await fetch('preview.json',{cache:'no-store'}).then(r=>r.json()));
  if(path==='/bootstrap')return d.bootstrap;
  if(path==='/people')return d.people;
  if(path==='/admin')return d.admin;
  if(path.startsWith('/guests/'))return {report:'Виктория Орлова\n\nСчета гостя\n• SONIC 2 · 2 840,00 $\n\nЗаработок без демо-счёта\nСегодня  +42,18 $\nНеделя   +186,40 $\nМесяц    +312,66 $\n\nДемо-счёт в расчёт не входит.'};
  if(path.startsWith('/cabinets/'))return {report:'Отчёт кабинета · CU-1\n\nЛичные стратегии: 2\nРезультат после комиссии: +684,32 $\nДемо-счёт исключён из итога.'};
  if(path.startsWith('/overview/report'))return previewReport(d,path,true);
  if(path.includes('/report'))return previewReport(d,path,false);
  throw new Error('Этот раздел недоступен в предпросмотре');
 }
 const isForm=options.body instanceof FormData;
 const headers={'X-Telegram-Init-Data':tg?.initData||'',...options.headers};
 if(!isForm&&!headers['Content-Type'])headers['Content-Type']='application/json';
 const response=await fetch(new URL('../api'+path,location.href),{...options,signal:AbortSignal.timeout(path==='/broadcast'?180000:20000),headers,cache:'no-store'});
 const d=await response.json().catch(()=>({error:'Сервер вернул некорректный ответ'}));
 if(!response.ok)throw new Error(d.error||`Ошибка ${response.status}`);
 return d;
}
async function loadReport(){const params=new URLSearchParams({period:state.period});if(state.period==='custom'){if(!state.from||!state.to)return null;params.set('from',state.from);params.set('to',state.to);}if(state.view==='overview'){params.set('currency',state.currency||Object.keys(state.data.totals)[0]||'USD');return api(`/overview/report?${params}`);}const acc=currentAccount();if(!acc)return null;state.login=acc.login;params.set('kind',state.kind);params.set('offset',state.offset);return api(`/accounts/${acc.login}/report?${params}`);}
async function refresh(quiet=false){
 if(state.busy){if(!quiet){state.pendingRefresh=true;generation++;}return;}
 state.busy=true;document.body.classList.add('is-loading');const gen=++generation;
 try{
  const data=await api('/bootstrap');if(gen!==generation)return;state.data=data;
  let report,people,admin;
   if(['overview','account','deals'].includes(state.view)){try{report=await loadReport();state.reportError='';state.report=report;}catch(error){state.report=null;state.reportError=error.message;}}
  if(state.view==='people')people=await api('/people');
  if(state.view==='settings'&&data.founder)admin=await api('/admin');
  const notifications=await api('/notifications').catch(()=>state.notifications);
  if(gen!==generation)return;
   if(people)state.people=people;if(admin)state.admin=admin;
  state.notifications=notifications;updateNotificationBadge();
  const newest=notifications.items?.[0];
  if(newest&&notifications.unread&&(!notificationsStarted||newest.id>lastNotificationId))
   eventToast(newest,notifications.unread);
  notificationsStarted=true;lastNotificationId=Math.max(lastNotificationId,newest?.id||0);
  if(!quiet||!document.querySelector('input:focus,textarea:focus,select:focus'))render();
 }catch(error){
  if(!state.data){if(!preview&&!tg?.initData){$('#main').innerHTML=authScreen();}else $('#main').innerHTML=empty('Не удалось открыть кабинет',error.message,button('refresh','Попробовать снова','primary','refresh'));}
  else if(!quiet)toast('Не удалось обновить данные. Показаны последние полученные значения.');
 }finally{state.busy=false;document.body.classList.remove('is-loading');if(state.pendingRefresh){state.pendingRefresh=false;await refresh();}}
}
async function navigate(){
 const [view,login]=location.hash.slice(1).split('/');
 const next=['overview','accounts','deals','account','people','settings'].includes(view)?view:'overview';
 if(state.filters[state.view])state.filters[state.view]={period:state.period,from:state.from,to:state.to};
 if(next!==state.view&&state.filters[next])Object.assign(state,state.filters[next]);
 state.view=next;
 if(login)state.login=Number(login);
 state.offset=0;state.kind='trades';state.report=null;state.reportError='';
 nav();if(state.data)render();
 await refresh();
 tg?.BackButton?.[state.view==='account'?'show':'hide']();
}
const SCHEMES=[['lime','Графит и лайм','dark','#111416',['#111416','#d0f29b','#b8a6e9']],['sapphire','Ночной сапфир','dark','#0e1420',['#0e1420','#8fc4ff','#c3b5ff']],['light','Светлая','light','#f4f5f0',['#f4f5f0','#537831','#79639e']]];
function currentScheme(){return document.documentElement.dataset.scheme||'lime';}
function setScheme(id,persist=true){const sc=SCHEMES.find(x=>x[0]===id)||SCHEMES[0],root=document.documentElement;root.dataset.scheme=sc[0];root.dataset.theme=sc[2];try{if(persist)localStorage.setItem('tag-scheme',sc[0]);}catch{}document.querySelector('meta[name="theme-color"]').content=sc[3];try{tg?.setHeaderColor(sc[3]);tg?.setBackgroundColor(sc[3]);}catch{}if(state.data&&state.view==='settings')render();}
function setTheme(theme,persist=true){setScheme(theme==='light'?'light':'lime',persist);}
function switchTheme(){const i=SCHEMES.findIndex(x=>x[0]===currentScheme());setScheme(SCHEMES[(i+1)%SCHEMES.length][0]);}
function dialog(title,body,label='Сохранить'){return new Promise(resolve=>{const d=$('#dialog');$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog-submit').textContent=label;const info=['Закрыть','Понятно','Готово'].includes(label);d.classList.toggle('info-only',info);d.onclick=e=>{if(info&&e.target===d)d.close('cancel');};d.returnValue='';d.onclose=()=>{const values=Object.fromEntries(new FormData($('form',d)));resolve(d.returnValue==='confirm'?values:null);};$('form',d).onsubmit=e=>{if(e.submitter?.value==='cancel')return;const fields=[...d.querySelectorAll('input,select,textarea')];if(!fields.every(f=>f.reportValidity()))e.preventDefault();};d.showModal();});}
async function confirm(title,text,label='Подтвердить'){return !!await dialog(title,`<p>${esc(text)}</p>`,label);}
async function mutate(path,data,method='POST'){await api(path,{method,body:data===undefined?undefined:JSON.stringify(data)});tg?.HapticFeedback?.notificationOccurred('success');toast('Сохранено. Изменения доступны и в боте.');await refresh();}
function field(label,name,type='text',value='',extra=''){return `<label class="field">${esc(label)}<input type="${type}" name="${name}" value="${esc(value)}" ${extra}></label>`;}
async function addAccount(){
 const known=[...new Set(state.data.accounts.filter(a=>!a.demo&&!a.shared).map(a=>a.cabinet).filter(Boolean))];
 const choice=known.length?`<label class="field">Кабинет<select name="cabinet_choice" id="add-cabinet-choice">${known.map(c=>{const owner=state.data.accounts.find(a=>a.cabinet===c)?.holder;return `<option value="${esc(c)}">${esc(owner?`${owner} · ${c}`:c)}</option>`;}).join('')}<option value="new">Другой кабинет…</option></select></label><div id="add-new-cabinet" hidden>${field('Customer Number нового кабинета','cabinet','text','','required disabled maxlength="32" placeholder="Например, CU228816"')}</div>`:field('Customer Number кабинета','cabinet','text','','required maxlength="32" placeholder="Например, CU228816"');
 const form=`<p>Используйте инвесторский пароль MT5: он даёт доступ к просмотру.</p>${choice}${field('Название стратегии','name','text','','required maxlength="48" placeholder="Например, SONIC или NEO"')}${field('Номер счёта MT5','login','number','','required min="1" step="1" placeholder="Например, 10001234"')}${field('Инвесторский пароль','password','password','','required maxlength="128" autocomplete="new-password" placeholder="Пароль инвестора MT5"')}<div class="auto-field"><span>Сервер и владелец</span><b>Определятся автоматически</b><small>После первой синхронизации с MT5</small></div>`;
 const data=await dialog('Подключить счёт MT5',form,'Подключить');if(!data)return;
 if(known.length){data.cabinet=data.cabinet_choice==='new'?data.cabinet:data.cabinet_choice;delete data.cabinet_choice;}
 await mutate('/accounts',data);location.hash='accounts';
}
async function configureAccount(login){const a=state.data.accounts.find(a=>Number(a.login)===Number(login));if(!a)return;const capital=!a.demo&&!a.shared?`${field('Капитал Invested','base','number',a.base??'','min="0" max="1000000000000" step="0.01"')}<p class="stat-note">Если указать сумму из портала, она станет основой расчёта капитала. Дальнейшие пополнения и выводы прибавятся автоматически.</p>${a.base!=null?'<label class="check"><input type="checkbox" name="reset_base"> Вернуть автоматический расчёт</label>':''}`:'';const body=`${a.demo?notice('Общий счёт для просмотра. Настройки уведомлений личные.'):field('Название стратегии','name','text',a.strategy||a.name,'required maxlength="48"')}<label class="check"><input type="checkbox" name="enabled" ${a.enabled?'checked':''}>${a.demo?'Показывать общий счёт':'Отслеживать счёт'}</label>${[['all','Все уведомления'],['trades','Сделки'],['deposits','Пополнения'],['withdrawals','Выводы']].map(([k,v])=>`<label class="check"><input type="checkbox" name="${k}" ${a.notify?.[k]!==false?'checked':''}>${v}</label>`).join('')}${capital}${!a.demo?`<div class="inline-actions mt">${button('delete-account','Удалить счёт из кабинета','danger small','',`data-login="${a.login}"`)}</div><p class="stat-note">Счёт у брокера и терминал останутся без изменений.</p>`:''}`;const values=await dialog('Настройки счёта',body);if(!values)return;const data={enabled:values.enabled==='on',notify:Object.fromEntries(['all','trades','deposits','withdrawals'].map(k=>[k,values[k]==='on']))};if(values.name)data.name=values.name;if(values.reset_base==='on')data.base=null;else if(values.base!==''&&values.base!==undefined&&Number(values.base)!==a.base)data.base=Number(values.base);await mutate(`/accounts/${a.login}`,data,'PATCH');}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();const action=el.dataset.action;if(el.disabled)return;el.disabled=true;try{
 if(action==='refresh')await refresh();
 else if(action==='notifications')await openNotifications();
 else if(action==='notification-open')await openNotification(el.dataset.id);
 else if(action==='notifications-read')await readAllNotifications();
 else if(action==='scheme')setScheme(el.dataset.value);
 else if(action==='pick-account'){state.login=Number(el.dataset.login);state.offset=0;state.report=null;state.reportError='';render();await refresh();}
 else if(action==='renew-link'){if(await confirm('Обновить ссылку?','Прежняя перестанет работать. Уже вошедшие гости останутся.','Обновить')){const token=String(state.people.link||'').split('start=')[1];await api('/invites/'+token,{method:'DELETE'});await refresh();toast('Ссылка обновлена');}}
 else if(action==='share-accounts'){const g=state.people.guests.find(x=>x.id===el.dataset.guest),have=new Set(g.accounts.filter(a=>a.shared).map(a=>String(a.login))),list=(state.people.shareable||[]).filter(a=>!have.has(String(a.login)));const d=await dialog('Открыть счета гостю',`${list.map(a=>`<label class="check"><input name="login-${a.login}" type="checkbox">${esc(a.name)}${a.cabinet?` · ${esc(a.cabinet)}`:''}</label>`).join('')}<p class="stat-note">Гость увидит их только для просмотра.</p>`,'Открыть');if(d){const logins=Object.keys(d).filter(k=>k.startsWith('login-')).map(k=>Number(k.slice(6)));if(logins.length)await mutate('/guests/'+el.dataset.guest,{action:'share',logins});}}
 else if(action==='toast-close')$('#toast').classList.remove('visible');
 else if(action==='shortcut')await addShortcut();
 else if(action==='strategy-info')await dialog('О стратегии',sonicStrategyCard(false),'Готово');
 else if(action==='theme')switchTheme();
 else if(action==='period'){if(state.period===el.dataset.value)return;state.period=el.dataset.value;state.offset=0;state.report=null;state.reportError='';if(state.period==='custom')render();else await refresh();}
 else if(action==='kind'){state.kind=el.dataset.value;state.offset=0;await refresh();}
 else if(action==='next'||action==='prev'){state.offset=Math.max(0,state.offset+(action==='next'?50:-50));await refresh();}
 else if(action==='apply-period'){state.from=$('#from-date').value;state.to=$('#to-date').value;if(!state.from||!state.to||state.from>state.to)throw new Error('Укажите корректные даты начала и конца');await refresh();}
 else if(action==='add')await addAccount();
 else if(action==='onboard-step')await mutate('/onboarding',{step:el.dataset.step,done:true});
 else if(action==='account-settings')await configureAccount(el.dataset.login);
 else if(action==='delete-account'){if($('#dialog').open)$('#dialog').close('cancel');if(await confirm('Удалить счёт?','Он исчезнет из вашего приложения и бота. Торговый счёт у брокера останется.','Удалить')){await mutate(`/accounts/${el.dataset.login}`,undefined,'DELETE');location.hash='accounts';}}
 else if(action==='restart'){if($('#dialog').open)$('#dialog').close('cancel');if(await confirm('Перезапустить терминал?','Это общий терминал агента. Опрос остальных счетов кратковременно прервётся.','Перезапустить'))await mutate('/actions',{action:'restart',login:Number(el.dataset.login)});}
 else if(action==='full-report'){await dialog('Отчёт Telegram-бота',`<div class="report-text">${esc(state.report.report)}</div>`,'Готово');}
 else if(action==='copy'){try{await navigator.clipboard.writeText(el.dataset.text);toast('Ссылка скопирована');}catch{throw new Error('Не удалось скопировать автоматически. Выделите и скопируйте ссылку.');}}
 else if(action==='cabinet-report'){const r=await api('/cabinets/'+encodeURIComponent(el.dataset.cabinet)+'/report?period=month');await dialog('Отчёт кабинета',`<div class="report-text">${esc(r.report)}</div>`,'Готово');}
 else if(action==='guest-detail'){const r=await api('/guests/'+el.dataset.guest);await dialog('Карточка гостя',`<div class="report-text">${esc(r.report)}</div>`,'Готово');}
 else if(action==='revoke-guest'){if(await confirm('Закрыть доступ гостю?','Ваши переданные счета исчезнут у гостя. Его личные счета и доступ к собственному кабинету сохранятся.','Закрыть доступ'))await mutate('/guests/'+el.dataset.guest,{action:'revoke'});}
 else if(action==='take'){if(await confirm('Забрать счёт у гостя?','Остальные счета гостя сохранятся.'))await mutate('/guests/'+el.dataset.guest,{action:'take',login:Number(el.dataset.login)});}
 else if(action==='alerts')await mutate('/actions',{action:'update_alerts',value:!state.data.update_alerts});
 else if(action==='leave'){if(await confirm('Отключить доступ?','Счета и приглашения в боте будут удалены. Для возвращения понадобится новое приглашение.','Отключить')){await api('/actions',{method:'POST',body:JSON.stringify({action:'leave'})});state.data=null;await refresh();}}
 else if(action==='broadcast'){
  const users=state.admin?.users||[];
  if(!users.length)throw new Error('Пока нет приглашённых пользователей для рассылки');
  const d=await dialog('Сообщение пользователям',`<div class="composer"><div class="composer-intro"><span class="eyebrow">РАССЫЛКА</span><p>Подготовьте сообщение и проверьте его перед отправкой.</p></div><label class="field">Кому<select name="target"><option value="all">Все приглашённые · ${users.length}</option>${users.map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('')}</select></label><div class="composer-editor"><div class="composer-editor-head"><b>Текст</b><span id="compose-count">0 / 4096</span></div><div class="compose-tools"><button type="button" class="format-btn" data-format="bold" aria-label="Жирный" title="Жирный"><b>Ж</b></button><button type="button" class="format-btn" data-format="italic" aria-label="Курсив" title="Курсив"><i>К</i></button><button type="button" class="format-btn" data-format="mono" aria-label="Моноширинный" title="Моноширинный"><code>М</code></button><button type="button" class="format-btn" data-format="quote" aria-label="Цитата" title="Цитата">❝</button><span>Выделите текст для оформления</span></div><textarea name="text" maxlength="4096" aria-label="Текст сообщения" placeholder="Напишите, что важно сообщить пользователям…"></textarea></div><label class="field composer-media">Фото или видео<input type="file" name="media" accept="image/jpeg,image/png,video/mp4"><small id="compose-file-name">JPG/PNG до 10 МБ · MP4 до 20 МБ</small></label><div class="composer-live"><span class="eyebrow">ПРЕДПРОСМОТР ТЕКСТА</span><div id="compose-live" class="compose-preview-text"><span class="muted">Сообщение появится здесь</span></div></div></div>`,'Проверить');
  if(!d)return;
  const file=d.media?.size?d.media:null;
  if(!String(d.text||'').trim()&&!file)throw new Error('Добавьте текст или файл');
  const kind=file?await mediaKind(file):null;
  if(file&&!kind)throw new Error('Выберите JPG, PNG или MP4');
  if(file&&file.size>(kind==='video'?20:10)*1024*1024)throw new Error('Фото до 10 МБ, видео до 20 МБ');
  const recipient=d.target==='all'?`все приглашённые (${users.length})`:users.find(u=>String(u.id)===String(d.target))?.name||'пользователь';
  const objectUrl=file?URL.createObjectURL(file):null;
  try{
   const media=file?`<div class="compose-preview-media">${kind==='photo'?`<img src="${esc(objectUrl)}" alt="Приложенное фото">`:`<video src="${esc(objectUrl)}" controls preload="metadata"></video>`}<small>${esc(file.name)} · ${fileSize(file.size)}</small></div>`:'';
   const body=`<p class="compose-recipient">Кому: <b>${esc(recipient)}</b></p>${media}<div class="compose-preview-text">${d.text?broadcastPreview(d.text):'<span class="muted">Без подписи</span>'}</div><p class="compose-footnote">Проверьте сообщение перед отправкой.</p>`;
   if(!await dialog('Проверка рассылки',body,'Отправить'))return;
  }finally{if(objectUrl)URL.revokeObjectURL(objectUrl);}
  if(preview){await dialog('Демо-режим',`<p>Макет показывает редактор и вложение, но не отправляет сообщения. Для настоящей рассылки откройте приложение из <a href="https://t.me/tagmarketgold_bot" target="_blank" rel="noopener">бота в Telegram</a>.</p>`,'Понятно');return;}
  const requestId=crypto.randomUUID();
  for(;;){
   const form=new FormData();form.append('target',d.target);form.append('text',d.text||'');form.append('request_id',requestId);if(file)form.append('media',file);
   let result;
   try{result=await api('/broadcast',{method:'POST',body:form});}
   catch(error){if(!await dialog('Отправка не завершена',`<p>${esc(error.message)}</p><p class="stat-note">Повтор с тем же сообщением не отправит его заново тем, кому оно уже доставлено.</p>`,'Проверить и повторить'))return;continue;}
   const done=`<div class="compose-status"><span>Доставлено</span><strong>${result.sent}</strong></div><div class="compose-status ${result.failed?'is-error':''}"><span>Ожидают повторной отправки</span><strong>${result.failed}</strong></div>`;
   if(!result.failed){await dialog('Сообщение отправлено',done,'Готово');return;}
   if(!await dialog('Отправлено частично',`${done}<p class="stat-note">Уже доставленные сообщения повторно не отправятся.</p>`,'Повторить недоставленным'))return;
  }
 }
 }catch(error){toast(error.message);}finally{el.disabled=false;}});
document.addEventListener('click',event=>{const tool=event.target.closest('[data-format]');if(!tool)return;event.preventDefault();const area=$('#dialog textarea[name="text"]');if(!area)return;const start=area.selectionStart,end=area.selectionEnd,selected=area.value.slice(start,end);const tags={bold:['<b>','</b>'],italic:['<i>','</i>'],mono:['<code>','</code>'],quote:['<blockquote>','</blockquote>']}[tool.dataset.format];if(!tags)return;area.setRangeText(tags[0]+selected+tags[1],start,end,'end');area.focus();area.setSelectionRange(start+tags[0].length,start+tags[0].length+selected.length);area.dispatchEvent(new Event('input',{bubbles:true}));});
document.addEventListener('input',event=>{if(event.target.matches('#dialog textarea[name="text"]')){const area=event.target,preview=$('#compose-live'),count=$('#compose-count');if(preview)preview.innerHTML=area.value?broadcastPreview(area.value):'<span class="muted">Сообщение появится здесь</span>';if(count)count.textContent=`${area.value.length} / 4096`;}});
 document.addEventListener('change',async event=>{try{if(event.target.matches('#dialog input[name="media"]')){const info=$('#compose-file-name');if(info)info.textContent=event.target.files?.[0]?`${event.target.files[0].name} · ${fileSize(event.target.files[0].size)}`:'JPG/PNG до 10 МБ · MP4 до 20 МБ';}if(event.target.id==='add-cabinet-choice'){const fresh=$('#add-new-cabinet');fresh.hidden=event.target.value!=='new';fresh.querySelector('input').disabled=fresh.hidden;}if(event.target.id==='account-select'){state.login=Number(event.target.value);state.offset=0;if(state.view==='account'){location.hash='account/'+state.login;}else await refresh();}if(event.target.id==='currency'){state.currency=event.target.value;state.report=null;await refresh();}}catch(error){toast(error.message);}});
$('#notifications').innerHTML=icon('bell');$('#refresh').innerHTML=icon('refresh');$('#refresh').addEventListener('click',()=>refresh());$('#theme').innerHTML=icon('sun');$('#theme').addEventListener('click',switchTheme);
let savedScheme;try{savedScheme=localStorage.getItem('tag-scheme')||(localStorage.getItem('tag-theme')==='light'?'light':null);}catch{}setScheme(savedScheme||(tg?.initData&&tg.colorScheme==='light'?'light':'lime'),false);
try{tg?.ready();tg?.expand();tg?.BackButton?.onClick(()=>{location.hash='accounts';});tg?.onEvent('themeChanged',()=>{let saved;try{saved=localStorage.getItem('tag-scheme')||localStorage.getItem('tag-theme');}catch{}if(!saved)setTheme(tg.colorScheme,false);});tg?.onEvent('homeScreenAdded',()=>toast('Ярлык Tag Markets добавлен на экран'));tg?.onEvent('homeScreenChecked',e=>{if(e?.status==='added')toast('Ярлык уже добавлен');});tg?.onEvent('homeScreenFailed',()=>toast('Telegram не смог добавить ярлык'));}catch{}
window.addEventListener('hashchange',navigate);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(true);});
 const originalSettingsView=settingsView;settingsView=function(){const url=state.data?.onboarding?.partner_url||'';return originalSettingsView()+`<section class="panel partner-link-panel"><div class="settings-row"><div><p>Партнёрская ссылка</p><small>${url?'Сохранена для будущих приглашений':'Добавьте персональную ссылку из IB Portal → Partner'}</small></div>${button('partner-link',url?'Изменить':'Добавить','secondary small')}</div></section>`;};
 navigate();refreshTimer=setInterval(()=>{if(!document.hidden&&!$('#dialog').open&&state.period!=='custom')refresh(true);},60000);

function networkView(){return `<div class="section-head"><h2>Доход партнёрской сети</h2></div><section class="panel"><p class="stat-note">По событиям портала · последние 30 дней с начислениями · валюта портала</p><div class="table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Сделок сети</th><th>Начислено</th></tr></thead><tbody>${state.admin.network.map(d=>`<tr><td>${esc(d.day)}</td><td>${number(d.trades)}</td><td class="positive">${number(d.income)}</td></tr>`).join('')}</tbody></table></div></section>`;}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-action="partner-link"]');if(!el)return;event.preventDefault();const current=state.data?.onboarding?.partner_url||'';const body=`<p>Откройте <a href="https://exfusion.ibportal.io" target="_blank" rel="noopener">IB Portal</a>, внизу справа откройте блок <b>Partner</b>, скопируйте свою персональную ссылку и вставьте её сюда.</p><label class="field">Партнёрская ссылка<input name="url" type="url" value="${esc(current)}" required placeholder="https://exfusion.ibportal.io/auth/register?..." /></label>`;const values=await dialog('Моя партнёрская ссылка',body,'Сохранить');if(!values)return;if(preview){await dialog('Демо-режим','<p>Персональная ссылка сохранится после входа через бота в Telegram. Здесь можно проверить вид формы без изменения вашего кабинета.</p>','Понятно');return;}try{const saved=await api('/profile/partner-link',{method:'PUT',body:JSON.stringify({url:values.url})});state.data.onboarding.partner_url=saved.url;toast('Партнёрская ссылка сохранена');render();}catch(error){toast('Ссылка не принята: проверьте адрес из блока Partner.');}});



